### ISSUE TITLE
'Check This File'-button in modal file-view doens't change the corresponding checkbox

### ISSUE THREAD

**Issue by Insensus** [yiisoft/yii2-gii#100]
### Issue
When previewing a file, the 'Check This File'-button at the top of the preview window doesn't change the checkbox corresponding to the file being previewed.
Instead, it always changes the checkbox corresponding to the last file in the list.

### Cause
The function *fillModal* in *gii.js:66* uses `$(this)` as if it points to the anchor-element corresponding to the file being previewed. In practice, though, it actually points to the Window-element.

### Proposed solution
Provide *fillModal* with the correct object through an extra argument.

**Comment by samdark** [comment]
Fixed with https://github.com/yiisoft/yii2-gii/commit/983a8b836c2097db553ace397358710ce89e1dfb. Thanks!
