### ISSUE TITLE
use the `enablePjax` option in crud generator to wrap the `ActiveForm` widget

### ISSUE THREAD

**Issue by Faryshta** [yiisoft/yii2-gii#115]
It can be tricky specially for what is being discussed on #99 so I propose to ONLY wrap the `ActiveForm` widget on a pjax and leave everything else as is.

**Comment by SilverFire** [comment]
I didn't get it. Could you elaborate your idea in details, please?

**Comment by samdark** [comment]
He wants to wrap forms generated with CRUD in PJAX.

**Comment by samdark** [comment]
@Faryshta do you mean that grids should not be wrapped?

**Comment by Faryshta** [comment]
i mean the grids should be wrapped but the active form should also be wrapped if `enablePjax` equals `true`.

The current functionality is good (tested it on one of my projects on console and web) I want to include a second `Pjax` widget this time on the `_form.php` generated file.

**Comment by SilverFire** [comment]
I've already said, that handling forms with PJAX is tricky. I see, that you suggest to wrap edit page only when `enablePjax` is `true`, but I'm still a little afraid of problems, tons of questions from the beginners, that might think `Oh, here is a checkbox, that it's easy as one click`.

**Comment by Faryshta** [comment]
> but I'm still a little afraid of problems, tons of questions from the beginners, that might think Oh, here is a checkbox, that it's easy as one click.

Isn't that a good reason to not enable things like I18N or things like `modelSearch` or the relations automatically generated on the model?

The gii generator is meant as a way to have an starting point which you can use to avoid repeating certain tasks.

If it works and executes as expected after using gii then a developer can move to keep on developing the system, even a newbie.

**Comment by cebe** [comment]
what is the reason to wrap the form in pjax?

**Comment by Faryshta** [comment]
to avoid refreshing the entire page when editing/saving and getting validation errors.

**Comment by SilverFire** [comment]
> Isn't that a good reason to not enable things like I18N or things like modelSearch or the relations automatically generated on the model?

I've got your thoughts, but `Yii::t` and search models are well documented and maintained by Yii team.

@Faryshta I'm not standing strongly against your idea.

**Comment by Faryshta** [comment]
`Pjax` widget is also well documented and maintained by the Yii team.

**Comment by SilverFire** [comment]
@Faryshta it has a bunch of non-obvious things. I called them _tricky things_ and posted in neighbor issue. We are maintaining a fork :) I see no reason to stuck on my opinion, I've elaborated my thoughts fully and have nothing to add yet. Let's wait for a word of other Yii team members.

**Comment by Faryshta** [comment]
i understand they are tricky and those are valid concerns. For example my biggest concern is what happens to links inside the `Pjax` widget but your other points seemed non-issues IMO.

**Comment by cebe** [comment]
I see the benefit of not reloading the page when navigating in the grid view but I do not think it is that useful to have form submission handled by pjax.
