### ISSUE TITLE
Problems with table prefix in Model Class

### ISSUE THREAD

**Issue by umanamente** [yiisoft/yii2-gii#116]
I am using table prefixes and have for example 2 tables connected with foreign keys:

     pref_pages
     pref_comments . pageid

When I generate models for that tables, **Model Class** fields are generated like `PrefComments` instead of `Comments`. It will be great to remove table prefix from the autogenerated **Model Class** field, because if there are relations, related models classes are generated without prefix (`Pages::className()` instead of `PrefPages::className()`):

    public function getPage()
		   {
		       return $this->hasOne(Pages::className(), ['pageid' => 'pageid']);
		   }
 
So I need to edit it manually.

**Comment by SilverFire** [comment]
Add `'tablePrefix' => 'pref_'` to your DB component configuration.

**Comment by umanamente** [comment]
Already existed, that doesn't change anything. Check [/assets/gii.js](https://github.com/yiisoft/yii2-gii/blob/177847f7b4ed07698a42d1e5f01bc792871210fb/assets/gii.js#L202-L212), there are no `tablePrefix` used in there.

**Comment by SilverFire** [comment]
Sorry, it seems that I didn't get your problem. 
Are you're talking about auto-generated model class names on client side?
After you change them on client side, do you have any problems with the generated files?

**Comment by umanamente** [comment]
Yeah, it's just the client side problem. Check the pull request.

**Comment by SilverFire** [comment]
https://github.com/yiisoft/yii2-gii/commit/402902fee3e5b4073aa98b2baa0414c6f38e0818
