### ISSUE TITLE
Bug model class name with 'table' name

### ISSUE THREAD

**Issue by adiramardiani** [yiisoft/yii2-gii#117]
I create a model using gii (database : SQL Server)
For example I create Realization & RealizationDetail Model in gii
I have table name 'TRealization' & 'TRealizationDetail'
In gii :
Table Name : TRealization / TRealizationDetail
Class Name : Realization / RealizationDetail

But i found bug in relations `Model::className()` give the table name like `TRealizationDetail::className()` and `TRealization::className()`, not `RealizationDetail::className()` or `Realization::className()`
```php

public function getTRealizationDetails(){
	return $this->hasMany(TRealizationDetail::className(), ['realization_id' => 'id']);
}

public function getRealization(){
        return $this->hasOne(TRealization::className(), ['id' => 'realization_id']);
}

[['realization_id'], 'exist', 'skipOnError' => true, 'targetClass' => TRealization::className(), 'targetAttribute' => ['realization_id' => 'id']],

```

**Comment by SilverFire** [comment]
Try to add `'tablePrefix' => 'T'` to your DB component configuration.

**Comment by adiramardiani** [comment]
No, because it's hard to use 'used' database, this database is already running by other application and the structure is not consistent and not good, like TRealization, TableUser, t_customer, etc So it's about `tablePrefix` it's about `tableName` with `className`
And then for this bug, I think the trouble in `(Should be Class not table)::className()`

**Comment by cebe** [comment]
@adiramardiani the class name is auto generated from the table name, you can use the table prefix T in gii to remove the prefix from the generated names. @SilverFire afaik there is a difference between gii table prefix field and the tablePrefix config in DB.

**Comment by cebe** [comment]
Oh, forget it, this was Yii 1.1 :)

**Comment by cebe** [comment]
related to #116?
