### ISSUE TITLE
Model generator: wrong relation names are generated for table names ending with "id"

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii2-gii#119]
- Import the following schema:

```sql
CREATE TABLE `test` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
);

CREATE TABLE `void` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `test_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_test` (`test_id`),
  CONSTRAINT `fk_test` FOREIGN KEY (`test_id`) REFERENCES `test` (`id`)
);
```

- Open Gii model generator. Preview generation of `Test` model.
- Instead of `getVoids()` there's `getVos()` relation.

**Comment by samdark** [comment]
The issue is here: https://github.com/yiisoft/yii2-gii/blob/master/generators/model/Generator.php#L626

**Comment by samdark** [comment]
Issue: no way to tell if it is a single word `void` or something with id at the end such as `parentid`.

**Comment by SilverFire** [comment]
I think we should tag it as `won't fix` because a fix will probably break other cases, where `id` tie should be removed.
