### ISSUE TITLE
Gii Model Generator fails with error when foreign key table is not in database.

### ISSUE THREAD

**Issue by davidjeddy** [yiisoft/yii2-gii#121]
To replicate:
 - Create two tables:Table A, Table B.
 - Set up a FK from Table B to Table A.
 - Remove Table A.
 - Try to generate model using Gii for Table B.

Table Prefix and Active Query.

**Comment by SilverFire** [comment]
It looks like an incorrect usage of DBMS. It's usually not allowed to drop a table but leave dependant FKs
