### ISSUE TITLE
Have you considered seperating the one model to be generated into one model and one relation trait.

### ISSUE THREAD

**Issue by vistart** [yiisoft/yii2-gii#122]
If current table contains foreign key references, or any fields referenced from other table fields, the model generator will generate "Relations" (`get<ModelName>()` methods) at the bottom of body of current model class to be generated.
Have you considered extracting the "Relations" into a seperated trait, such as named `<ModelName>RelationTrait`?
If only to add foreign key references without modifying column definitions of table each time, if do so, then will generate new RelationTrait, without modifying model.

**Comment by samdark** [comment]
No. What's the benefit of having these?

**Comment by vistart** [comment]
Maybe a model contains more than dozens of relations. The relations and rules are responsible for different developers (File-centric) . To prevent more than one developer to modify the same file, the leader would divide the generated model into model with definition and trait with relations in advanced， and then assign them to the developer in charge of each file.

**Comment by samdark** [comment]
Sounds like separate domains using same database tables. Worth creating different sets of models for the same tables in this case. I don't think traits are any good to solve the issue.
