### ISSUE TITLE
messages should be traslate in yii.php?

### ISSUE THREAD

**Issue by pana1990** [yiisoft/yii2-gii#123]
this [messages](https://github.com/yiisoft/yii2-gii/blob/master/generators/model/form.php#L16) should be traslation in yii.php core?

**Comment by SilverFire** [comment]
Looks like that. We must create a yii2-gii specific dictionary.

**Comment by cebe** [comment]
hm... not sure why they are there. they are the only messages used in Gii as far as I see.
Imo they should be removed as the whole interface of Gii is english only.

**Comment by pana1990** [comment]
@cebe +1 , can i pullreques for this issue?

**Comment by SilverFire** [comment]
Yeah, we've discussed it with @samdark in PM and decided to drop these `Yii::t`. Feel free to submit a PR

**Comment by pana1990** [comment]
@samdark :+1:
