### ISSUE TITLE
Model generator - Ajax validation breaks form submission

### ISSUE THREAD

**Issue by beukeshu** [yiisoft/yii2-gii#126]
I am using Postgresql database, and things go wrong when I use a table name containing a schema.

This sequence of actions causes the bug:

1. I add the table name in the "Table Name" field (eg. my.newtable)
2. When the browser unfocusses from that field, a model name is automatically generated for the "Model Name" field, "My.newtable". But this generated name contains a period character, causing the error "Only word characters are allowed."
3. All is normal up to this point. Then, I remove the period character from the "Model Name" field, which causes the validation error to go away
4. When I then click the "preview" button, **nothing happen** except the browser scrolling up to the "Model Name" field. The (valid) form does not get submitted at all.

To work around this problem, I do the following:

1. Refresh the /gii/default/view?id=model view
2. Fill in the "Model Name" field **first**, so that it does not get autopoplated with the invalid period character from the table name. Thus, the validation error never triggers
3. Then I fill in the table name, and continue as usual

The quick fix is likely to strip out any periods in Gii's model Generator:generateClassName() method. It is generating model names which are invalid.

**Comment by samdark** [comment]
Merged. Thanks!
