### ISSUE TITLE
Using viaTable() or via() method

### ISSUE THREAD

**Issue by LAV45** [yiisoft/yii2-gii#14]
Why gii Model generator, by default, creates links between different models using the method viaTable() and not via()
```php
public function getPageTags()
{
    return $this->hasMany(PageTags::className(), ['page_id' => 'id']);
}

public function getTags()
{
    return $this->hasMany(Tag::className(), ['id' => 'tag_id'])
        //->viaTable('page_tag', ['page_id' => 'id']);
        ->via('pageTags');
}
```

if you change table name then it will have to fix in a few places

**Comment by cebe** [comment]
in most cases you do not need a model for the junction table. Gii generates code for the most common case.

**Comment by LAV45** [comment]
@samdark, what do you think about this?

I already have finished and tested the solution, I just need your approval.

**Comment by samdark** [comment]
As @cebe said, using tables is a bit more common.
