### ISSUE TITLE
Copy from generated code creates unexpected characters

### ISSUE THREAD

**Issue by prabowomurti** [yiisoft/yii2-gii#145]
### What steps will reproduce the problem?
Use Gii to generate code (CRUD Generator). Using Cmd + C will copy the generated code. Paste it to text editor (Sublime Text 2 or any other text editor), run the code with the browser.

### What's expected?

The code is running smoothly.

### What do you get instead?

Get "Unexpected syntax" error. The "space" becomes ` ` character (looks like a space but it's not.).

![screen shot 2016-04-03 at 17 04 32](https://cloud.githubusercontent.com/assets/38052/14231882/3e8908e0-f9be-11e5-9493-c2b06b6ee995.png)

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.7
| PHP version      | 5.5.30
| Operating system | OSX 10.10.5
| Browser | Chrome Version 49.0.2623.108 (64-bit)

**Comment by cebe** [comment]
could you try other browsers if they show the same behavior?
