### ISSUE TITLE
generate code with gii but keep customization

### ISSUE THREAD

**Issue by lorinczelod** [yiisoft/yii2-gii#15]
I made my model generator, because the existing one not keep my changes in model class, if I regenerate the model for example after a table structure changing.

1. The first idea is, that we make two class instead of one:
First class:
```php
<?php
namespace app\models\db\core;
/**
 * This is the model class for table "article".
 * @property integer $id
 * @property string $title
 * ......
 */
 
class CoreArticle extends \yii\db\ActiveRecord {
    /** @inheritdoc */
    public static function tableName()   {
        return 'article';
    }
 // ......
 }
 ```
Second class:
```php
<?php
namespace app\models\db;
/** This is the override model class for table "article". */
class Article extends \app\models\db\core\CoreArticle
{ 
}
```
This second class is empty at the beginning, but here will come the customization, and never will be regenerated.

2. The second idea is that these model classes from tables we put e.g. to "db" subdirectory, and "core" sub-subdir respectively

**Comment by lorinczelod** [comment]
I saw cebe response, but I put on wrong place my propose, so I copy here too.
cebe: please write down here too your response

**Comment by cebe** [comment]
https://github.com/yiisoft/yii2/issues/7891#issuecomment-86749228
