### ISSUE TITLE
debug tool bar does not show

### ISSUE THREAD

**Issue by shyandsy** [yiisoft/yii2-gii#150]
### What steps will reproduce the problem?
setup new basic template project by composer 

### What's expected?
1.debug toolbar does not show up
2.upload to remote  server
3.add the local ip, config\web.php line 60
 ```php
if (YII_ENV_DEV) {
    // configuration adjustments for 'dev' environment
    $config['bootstrap'][] = 'debug';
    $config['modules']['debug'] = [
        'class' => 'yii\debug\Module',
    ];

    $config['bootstrap'][] = 'gii';
    $config['modules']['gii'] = [
        'class' => 'yii\gii\Module',
        'allowedIPs' => ['24.79.94.68'] // adjust this to your needs
    ];
}
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       |                   2.0.7
| PHP version      |               7.0.3
| Operating system |            centos 7 x64

**Comment by samdark** [comment]
Is that somehow connected to Gii?

**Comment by shyandsy** [comment]
not sure. But go works correct

2016年4月16日星期六，Alexander Makarov <notifications@github.com> 写道：

> Is that somehow connected to Gii?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/yiisoft/yii2-gii/issues/150#issuecomment-210841151>
>


-- 
Yang Shi
201-15 bridgeland dr south
R3Y 0E7

**Comment by shyandsy** [comment]
@samdark  sorry I posted on wrong place

**Comment by Faryshta** [comment]
https://github.com/yiisoft/yii2-debug/issues/101
