### ISSUE TITLE
Got the warning message: array_flip(): Can only flip STRING and INTEGER values!

### ISSUE THREAD

**Issue by littlerun** [yiisoft/yii2-gii#155]
### What steps will reproduce the problem?
1)Go to the "Model Generator" page and create a model based on an exist table 'project';
2)Preview the model by clicking the button ''Preview"

### What's expected?
I expected the preview page of the specified model.

### What do you get instead?
I got the warning message below:
`
PHP Warning – yii\base\ErrorException
array_flip(): Can only flip STRING and INTEGER values!
in yii2-gii\generators\model\Generator.php at line 463`

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       |  2.0.8 dev
| PHP version      |  5.5.8
| Operating system | Windows 7 

#### Form data
_csrf:cVA2eGtoTl87M3weGQogZyghdBckJwJoNxN3KTlfeBEGJFsdWA4YEQ==
Generator[tableName]:project
Generator[modelClass]:Project
Generator[ns]:common\models
Generator[baseClass]:yii\db\ActiveRecord
Generator[db]:db
Generator[useTablePrefix]:0
Generator[generateRelations]:all
Generator[generateLabelsFromComments]:0
Generator[generateQuery]:0
Generator[queryNs]:common\models
Generator[queryClass]:ProjectQuery
Generator[queryBaseClass]:yii\db\ActiveQuery
Generator[enableI18N]:0
Generator[messageCategory]:app
Generator[useSchemaName]:0
Generator[useSchemaName]:1
Generator[template]:default

**Comment by samdark** [comment]
Could you post SQL to create that project table.

**Comment by littlerun** [comment]
@samdark Thanks for your reply, I created that table through the command `migrate`.

`
use yii\db\Migration;
class m160426_100645_project extends Migration
{
    public function up()
    {
        $tableOptions = null;
        if ($this->db->driverName === 'mysql') {
            $tableOptions = 'CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE=InnoDB';
        }//endif
        $this->createTable('project', [
            'id' => 'int(11) unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY',
            'name' => "varchar(512) NOT NULL DEFAULT '' COMMENT 'project name'",
            'create_time' =>     "int(10) unsigned NOT NULL COMMENT 'create time'", 
            'update_time' =>     "int(10) unsigned NOT NULL COMMENT 'update time'"
        ], $tableOptions);
        $this->addColumn('subject_course', 'project_id', 'int(11) unsigned NOT NULL COMMENT "project id"');
    }
    public function down()
    {
        echo "m160426_100645_project cannot be reverted.\n";
        $this->dropColumn('subject_course', 'project_id');
        $this->dropTable('project');

        return true;
    }
}`

**Comment by Faryshta** [comment]
the problem is with the references. you should check your foreign keys and see if any of them is corrupted. For example on your migration you didn't added any foreign key to the column `project_id` in the `subject_course` table

**Comment by asmythe** [comment]
Just upgraded to 2.0.10 and am getting this same error. Table could not be simpler. Here's the create

CREATE TABLE `tour` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `tour_time` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

But I don't think the problem is with this table. It is failing on generators/model/Generator on line 463:

                    $link = $this->generateRelationLink(array_flip($refs));

Looks like it is assembling relations from all the tables.

**Comment by samdark** [comment]
Can you dump `$refs`?

**Comment by asmythe** [comment]
That got me pointed in the right direction. Somehow I had a unique key and a foreign key constraint with the same name. Once I cleaned that up, it works fine. THANK YOU!
