### ISSUE TITLE
The controller has been generated successfully. You may try it now. *wrong link*

### ISSUE THREAD

**Issue by Lordfef** [yiisoft/yii2-gii#182]
hi all, i'm using gii to generate only my controller.
I want to create it in my directory "app\controllers\set\MyController"

I generate without problem and it tell me: The controller has been generated successfully. You may try it now
The link point to: http://mydomain.com/my/index
but it generate 404 not found because the right link is: http://mydomain.com/set/my/index

i don't know if it's a bug or not.
Bye

**Comment by SilverFire** [comment]
The controller must be located under `controllers` directory. If you want to prefix it with `set` - pack it in the `set` module, or simply configure rule in `UrlManager`.

Read [runtime ruting](http://www.yiiframework.com/doc-2.0/guide-runtime-routing.html#using-pretty-urls) section of the Yii definite guide to know how

**Comment by cebe** [comment]
@SilverFire controllers can be located in subdirectories:

http://www.yiiframework.com/doc-2.0/guide-structure-controllers.html#controller-ids

**Comment by SilverFire** [comment]
:fearful: shame on me
