### ISSUE TITLE
Generate Relations from Current Schema exception

### ISSUE THREAD

**Issue by sukvojte** [yiisoft/yii2-gii#186]
### What steps will reproduce the problem?
Open Gii and try generate model from a MySQL5.7 table with 'Generate Relations from Current Schema' set to TRUE.

### What's expected?
Generated model or correct error warning when is defaultSchema empty, or automatically set schema from connection.

### What do you get instead?
Exception:
> Database Exception – yii\db\Exception
> SQLSTATE[42000]: Syntax error or access violation: 1102 Incorrect database name ''
> The SQL being executed was: SHOW TABLES FROM ``
> 
> Error Info: Array
> (
>     [0] => 42000
>     [1] => 1102
>     [2] => Incorrect database name ''
> )

### Additional info

This hapends when Yii::$app->db->schema->defaultSchema is empty. But MySQL does not use default schema for user. 
This bug bring commit fb52694ec523bb82ca73e0173f1b96c5c2ff3d5d with new 'Generate Relations from Current Schema' option.

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.10-dev
| PHP version      |  PHP 7.0.9
| Operating system |  Win 8.1 64bit

**Comment by samdark** [comment]
That's code from `master` branch, right?

**Comment by uldisn** [comment]
I fixed change in yii2-gii\generators\model\Generator.php row 455 :

```php
$schemaNames = ($this->generateRelationsFromCurrentSchema) ? [$db->schema->defaultSchema] : $this->getSchemaNames();
```

```php
$schemaNames = $this->getSchemaNames();
```

**Comment by samdark** [comment]
Great. Could you send a pull request?

**Comment by samdark** [comment]
Oh. Looking at diff I see that it has a configurable feature removed.

**Comment by uldisn** [comment]
$db->schema->defaultSchema must get actual table, but $this->getSchemaNames() do same.

**Comment by samdark** [comment]
@zlakomanoff any comments?

**Comment by zlakomanoff** [comment]
@samdark i will check and fix tomorrow

**Comment by zlakomanoff** [comment]
@samdark @uldisn @cornernote @nergal @cebe 

MySQL $defaultSchema always is empty 

`
$defaultSchema	string	The default schema name used for the current session.
`

I think mysql **$defaultSchema** must contain current database name.
http://dev.mysql.com/doc/refman/5.7/en/information-functions.html#function_database

sqlite - the same issue, but this db have no schemas or db names (?)
oracle  - fine, all users have schema with the same name as user
mssql - wrong, need setup current schema (?)
pgsql - always 'public', i think its wrong too
cubrid - always empty, like a mysql
