### ISSUE TITLE
Controller names with _ aren't generated properly

### ISSUE THREAD

**Issue by RustemS** [yiisoft/yii2-gii#218]
What steps will reproduce the problem?
1. Open the Controller Generator
2. Fill Controller Class        frontend\controllers\Mariy_elController
3. Fill Action IDs                 index, experiment
4. Click Generate

What's expected?
I would like it   mariy_el
like this - http://test.ru/mariy_el/index.php        
like this - http://test.ru/mariy_el/experiment.php   

What do you get instead?
What is it?  mariy-el, here (-). I would like it  mariy_el, here (_).
but the error occurs when the pass by reference try it now.
http://test.ru/mariy-el/index.php                 Not Found (#404)
http://test.ru/mariy-el/experiment.php       Not Found (#404)

if you create without gii, then everything works fine
controllers\Mariy_elController.php
views\mariy_el\experiment.php
views\mariy_el\index.php

Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 5.6.22
| Operating system | windows 7

**Comment by uldisn** [comment]
After generation rename controller class and view paths.

**Comment by MKiselev** [comment]
I was localized issue.

See https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseInflector.php#L389

Specific here ```str_replace('_', $separator```...

All ```_``` will be replaced to ```$separator```.

**Comment by samdark** [comment]
For Gii — certainly not.

**Comment by MKiselev** [comment]
@samdark okay. Then I just will fix it in Gii.
