### ISSUE TITLE
Update View Submit button Label as Save

### ISSUE THREAD

**Issue by pptyasar** [yiisoft/yii2-gii#234]
When creating CRUD from gii. Update button have in update view have label as update 
It is little bit confusing . When user click update button update page is rendered . But in submit  button also have update label.

It is better have label as save instead update in submit button of update view.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0
| PHP version      | 5.6
| Operating system | Ubuntu

**Comment by samdark** [comment]
Hmm... isn't "Update" as action clear?

**Comment by samdark** [comment]
Actually I agree with the suggestion.
