### ISSUE TITLE
Use int/bool instead of integer/boolean in doc blocks

### ISSUE THREAD

**Issue by klimov-paul** [yiisoft/yii2-gii#238]
### What steps will reproduce the problem?

Generate ActiveRecord for table containing interger or boolean fields

### What's expected?

Generated class PHPDocs displays attribute types in short name (PHP7 style). e.g. `@property int $id`

### What do you get instead?

Generated class PHPDocs displays attribute types in full name e.g. `@property integer $id`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | *
| PHP version      | *
| Operating system | *

Back at Yii2 project there was a decision made to switch long names for `integer` and `boolean` types to the short ones: `int` and `bool` to match type names introduced by PHP 7.

See https://github.com/yiisoft/yii2/issues/12055

**Comment by samdark** [comment]
Yes. Should be adjusted.
