### ISSUE TITLE
Modules and their nested modules

### ISSUE THREAD

**Issue by RustemS** [yiisoft/yii2-gii#247]
### What steps will reproduce the problem?
modules 
Test 
      |__ controllers
      |__ models    /* embedded module name Test2*/
      |__ views                                                              

Experiment 
                |__ controllers
                |__ models    /* embedded module name Experiment2 */
                |__ views  

There are 2 modules Test and Experiment, they have invested in the units that have the same controllers and actions  category/news

### What's expected?
The problem is that when calling nested modules
http: // localhost / test2 / category / news
or
http: // localhost / experiment2 / category / news
It shows the type / news, which is a priority on the rules while the rules prescribed for each separately.

Question: Why does the form / news shows are not on their embedded module, if the rule above?
If the rule is reversed, becoming the contrary view is shown / news another sub-module?

### Additional info
But in Test Modules and Experiment everything works correctly when called with the same controller and action category/news
http: // localhost / test / category / news
or
http: // localhost / experiment / category / news
there does not intersect anything.
What can be said about the sub-modules?

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11
| PHP version      | 7.1.0
| Operating system | Windows 7

**Comment by samdark** [comment]
Is the issue about Gii code generator?

**Comment by RustemS** [comment]
The problem is partially solved, if it is hard to prescribe rules for all sub-modules, the question of how not to clutter the overall configuration rules for all sub-modules, and to prescribe rules to a separate config file, which is specifically to treat certain embedded module?

**Comment by samdark** [comment]
The issue is reported into Gii repository so I'm asking again: is it code generation related or not?

**Comment by RustemS** [comment]
Gii is working on the creation of the module and sub-modules properly tested.

**Comment by RustemS** [comment]
The problem is how to make the rules of nested modules are not in the general application configuration, and in a separate configuration file.

**Comment by samdark** [comment]
That sounds like general question which should be asked in a forum. As for the answer, look at bootstrapping process.

**Comment by dynasource** [comment]
you can split your configuration files in different files per module. This makes sense when you have detailed configuration for specific modules. An example for components is given at http://www.yiiframework.com/doc-2.0/guide-concept-configurations.html#configuration-files

**Comment by Saltindestructible** [comment]
> you can split your configuration files in different files per module. This makes sense when you have detailed configuration for specific modules. An example for components is given at http://www.yiiframework.com/doc-2.0/guide-concept-configurations.html#configuration-files





https://receding-gravity-forms-p.github.io/q6YJ0lmCjRYCzc5NbH6XdaH3ybZOKz8/
