### ISSUE TITLE
Gii should generate unique validator for tables with multiple primary keys

### ISSUE THREAD

**Issue by dmirogin** [yiisoft/yii2-gii#249]
### What steps will reproduce the problem?
Table for example
```sql
CREATE TABLE "product_to_category" (
  product_id INTEGER NOT NULL,
  category_id INTEGER NOT NULL,
  PRIMARY KEY (product_id, category_id)
);
```
### What's expected?
Unique validator in rules section like that
```php
[['product_id', 'category_id'], 'unique', 'targetAttribute' => ['product_id', 'category_id'], 'message' => '']
```

### What do you get instead?
Nothing :smiley: 

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11

**!Update**
I've not encountered this issue in sqlite, because sqlite does primary keys unique.

**Comment by dmirogin** [comment]
I updated my comment.
Should i add specific test for postgresql or mysql  ?

**Comment by samdark** [comment]
Yes. Would be good.
