### ISSUE TITLE
Getting unknown property: yii\mongodb\Connection::driverName

### ISSUE THREAD

**Issue by klimov-paul** [yiisoft/yii2-gii#255]
### What steps will reproduce the problem?

Generate CRUD with `yii\mongodb\ActiveRecord` model

### What's expected?

CRUD generated

### What do you get instead?

Exception: Getting unknown property: yii\mongodb\Connection::driverName

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11
| PHP version     | *
| Operating system | *

Issue migration from https://github.com/yiisoft/yii2-mongodb/issues/191
Problem is caused by recent change intoduced at https://github.com/yiisoft/yii2-gii/pull/244

**Comment by samdark** [comment]
`instanceof` check should be added to https://github.com/yiisoft/yii2-gii/pull/244/files#diff-845dc1c0edaf084ad61401bedfccce75R564

**Comment by MKiselev** [comment]
@samdark okay, my mistake. Will be fixed soon.
