### ISSUE TITLE
GII CRUD: flash messages after actions

### ISSUE THREAD

**Issue by lukBarros** [yiisoft/yii2-gii#26]
Hi mans!

It reported in https://github.com/yiisoft/yii2/issues/3428#issuecomment-93170751

say...

@lucianobaraglia  commented on 11 May 2014
I think it would be nice having flash messages in crud after common actions were performed.
For example, after deleting something, I would expect to read: "The item was successfully deleted", and after creating or updating: "The item was created/updated successfully".

Or something like that.

I will code this change , some opposition ?

**Comment by samdark** [comment]
There's no common method for displaying flash messages currently. How do you want to handle it?

**Comment by lukBarros** [comment]
I sorry! My english..... :(

Look method create, update, delete 

Usage for success:

Yii::$app->session->setFlash('success',<?= $generator->generateString('string') ?>);

or for erro, danger or fail

Yii::$app->session->setFlash('danger',<?= $generator->generateString('string') ?>) ?>);

**Comment by lukBarros** [comment]
@samdark  o que acha?

**Comment by samdark** [comment]
But how to display these messages?

**Comment by lukBarros** [comment]
If call in my views or my templates views:

Alert::widget()


It show automatic, all set Flash Msg via:


Yii::$app->session->setFlash('type','string')

@samdark test it!

**Comment by samdark** [comment]
Which `Alert`?

**Comment by lukBarros** [comment]
Success and Danger...

create, update and delete set or flash success or danger msg for action passed or failed.... ok?

**Comment by samdark** [comment]
I mean which widget will be used?

**Comment by lukBarros** [comment]
i did not understand you... please explain better.

**Comment by samdark** [comment]
You want do display flash messages. By default there's nothing in the application to do it. Do you suggest   adjusting application templates somehow?

**Comment by lukBarros** [comment]
ok I'm thinking ...

**Comment by lukBarros** [comment]
Man, i have a sample for it based in the delete router.

In the ConfiguracaoCalendarioController.php 

'''''
public function actionDelete($id)
    {
        
        try {
            $this->findModel($id)->delete();
        } catch (yii\db\IntegrityException $e) {
            if($e->getCode() == 23000){
                Yii::$app->session->setFlash('danger',Yii::t('app', 'Record can not be deleted, there is a relation  associated with it'));
                return $this->redirect(['index']);
            }
        }
        
        Yii::$app->session->setFlash('success',Yii::t('app', 'deleted successfully'));      
        return $this->redirect(['index']);
    }


public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->loadAndSave(Yii::$app->request->post())) {
            Yii::$app->session->setFlash('success',Yii::t('app', 'Updated successfully!'));
            return $this->redirect(['index']);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }


 public function actionCreate()
    {
        $model = new ConfiguracaoCalendario();

        if ($model->loadAndSave(Yii::$app->request->post())) {
            Yii::$app->session->setFlash('success',Yii::t('app', 'Saved successfully!'));
            return $this->redirect(['index']);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }
''''

In the views of the model  (in the views /configuracao-calendario/ folder) or in the template, in our case we adopt this use the template to not pollute views.


'''''
<?= Alert::widget() ?>
'''''

This is enough to show success and danger flash types.

I do not know how, but inside the widget ALERT he somehow already take what has setted as Flash Messaging these two types of identifier and shows automatically, I do not know if you know this detail Alert widget.

**Comment by LAV45** [comment]
```php
try {
    $this->findModel($id)->delete();
} catch (yii\db\IntegrityException $e) {
...
}
```
In the admin, in debug mode I would like to see all errors.

```php
if ($model->loadAndSave(Yii::$app->request->post())) {
...
}
```
Why to join the already simple method load() and save()?
It only reduces the flexibility in describing the actions of creating (for example).

**Comment by lukBarros** [comment]
Dont look it detal. It is util for my project.

Please focus on flash msgs seters and alert usege for show. Ok?

**Comment by realtebo** [comment]
+1 for this feature

**Comment by lukBarros** [comment]
@samdark  look it please.

**Comment by xiandalisay** [comment]
This is very usable especially for beginners. For example (inserting a table row), if there are input and insertion errors, specific errors will be displayed. Errors can be displayed through the alert widget. Other developers would want more specific usages like displaying errors after triggering beforeValidate, beforeSave(), etc...

**Comment by lukBarros** [comment]
@xiandalisay  reality!!! It is util, very util!.....

@samdark what you think about it?

**Comment by samdark** [comment]
I think we won't have it out of the box because some templates such as basic don't have support for displaying such messages.
