### ISSUE TITLE
Exception handling any method exclude the control

### ISSUE THREAD

**Issue by lukBarros** [yiisoft/yii2-gii#27]
Exception handling any method exclude the control.

The simple try { } catch { }?

**Comment by klimov-paul** [comment]
Please, clarify

**Comment by samdark** [comment]
?

**Comment by lukBarros** [comment]
If access delete actions in the you controller, and have FK erro delete, its show yii2 exception.

Look my delete in legba-gii template set https://github.com/id5/legba-gii/blob/master/crud/advanced/controller.php

Try and Catch in te delete();

**Comment by lukBarros** [comment]
Look #26 please.

**Comment by lukBarros** [comment]
Look #26, duplicate it. Close. Thanks! Goto #26....
