### ISSUE TITLE
Missing required parameter "id" when instantiating "yii\gii\Module".

### ISSUE THREAD

**Issue by gaoyong06** [yiisoft/yii2-gii#275]
I can not use gii after installation. The error message is as follows.
-------------
Invalid Configuration – yii\base\InvalidConfigException
Missing required parameter "id" when instantiating "yii\gii\Module".
------------
### track log
------------
Invalid Configuration – yii\base\InvalidConfigException

Missing required parameter "id" when instantiating "yii\gii\Module".
1. in /PATH/vendor/yiisoft/yii2/di/Container.php at line 460
451452453454455456457458459460461462463464465466467468469    protected function resolveDependencies($dependencies, $reflection = null)
    {
        foreach ($dependencies as $index => $dependency) {
            if ($dependency instanceof Instance) {
                if ($dependency->id !== null) {
                    $dependencies[$index] = $this->get($dependency->id);
                } elseif ($reflection !== null) {
                    $name = $reflection->getConstructor()->getParameters()[$index]->getName();
                    $class = $reflection->getName();
                    throw new InvalidConfigException("Missing required parameter \"$name\" when instantiating \"$class\".");
                }
            }
        }
        return $dependencies;
    }
 
    /**
     * Invoke a callback with resolving dependencies in parameters.
     *
2. in /PATH/vendor/yiisoft/yii2/di/Container.php at line 370 – yii\di\Container::resolveDependencies([yii\di\Instance, null, []], ReflectionClass)
3. in /PATH/vendor/yiisoft/yii2/di/Container.php at line 156 – yii\di\Container::build('yii\gii\Module', [], [])
4. in /PATH/vendor/yiisoft/yii2/BaseYii.php at line 344 – yii\di\Container::get('yii\gii\Module', [], [])
5. in /PATH/vendor/yiisoft/yii2/di/ServiceLocator.php at line 135 – yii\BaseYii::createObject(['class' => 'yii\gii\Module'])
6. in /PATH/vendor/yiisoft/yii2/base/Application.php at line 307 – yii\di\ServiceLocator::get('gii')
7. in /PATH/vendor/yiisoft/yii2/web/Application.php at line 69 – yii\base\Application::bootstrap()
8. in /PATH/vendor/yiisoft/yii2/base/Application.php at line 272 – yii\web\Application::bootstrap()
9. in /PATH/vendor/yiisoft/yii2/base/Object.php at line 107 – yii\base\Application::init()
10. in /PATH/vendor/yiisoft/yii2/base/Application.php at line 205 – yii\base\Object::__construct(['components' => ['cache' => ['class' => 'yii\caching\FileCache'], 'db' => ['class' => 'yii\db\Connection', 'dsn' => 'mysql:host=localhost;dbname=yii2...', 'username' => 'root', 'password' => '', ...], 'mailer' => ['class' => 'yii\swiftmailer\Mailer', 'viewPath' => '@common/mail', 'useFileTransport' => true], 'request' => ['csrfParam' => '_csrf-backend', 'cookieValidationKey' => '1u52wXBKtxJDvsfNHLZj7NKHQKOxm4um', 'class' => 'yii\web\Request'], ...], 'id' => 'app-backend', 'controllerNamespace' => 'backend\controllers', 'bootstrap' => ['log', 'debug', 'gii'], ...])
11. in /PATH/backend/web/index.php at line 17 – yii\base\Application::__construct(['vendorPath' => '/PATH...', 'components' => ['cache' => ['class' => 'yii\caching\FileCache'], 'db' => ['class' => 'yii\db\Connection', 'dsn' => 'mysql:host=localhost;dbname=yii2...', 'username' => 'root', 'password' => '', ...], 'mailer' => ['class' => 'yii\swiftmailer\Mailer', 'viewPath' => '@common/mail', 'useFileTransport' => true], 'request' => ['csrfParam' => '_csrf-backend', 'cookieValidationKey' => '1u52wXBKtxJDvsfNHLZj7NKHQKOxm4um'], ...], 'id' => 'app-backend', 'basePath' => '/PATH...', ...])
11121314151617    require(__DIR__ . '/../../common/config/main.php'),
    require(__DIR__ . '/../../common/config/main-local.php'),
    require(__DIR__ . '/../config/main.php'),
    require(__DIR__ . '/../config/main-local.php')
);
 (new yii\web\Application($config))->run();

----------
### composer.json
----------
  ....
"require-dev": {
        "yiisoft/yii2-debug": "~2.0.0",
        "yiisoft/yii2-gii": "~2.0.0",
        "yiisoft/yii2-faker": "~2.0.0",
        "codeception/base": "^2.2.3",
        "codeception/verify": "~0.3.1"
    },
   ....

----------
### Additional info
----------
| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2 Yii PHP Framework Version 2
| PHP version      | PHP 5.6.29 (cli) (built: Dec 10 2016 16:14:37)
| Operating system | Linux iZ23bo9k3mkZ 2.6.32-431.23.3.el6.x86_64 #1 SMP Thu Jul 31 17:20:51 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by samdark** [comment]
How did you installed it? Could you provide a step by step description on how to reproduce it?

**Comment by linslin** [comment]
This happends on a fresh install via `composer create-project --prefer-dist yiisoft/yii2-app-basic basic` than just add 

```
'gii' => [
    'class' => 'yii\gii\Module',
],
```
into your configuration file.

**Comment by samdark** [comment]
Well, that's obviously wrong configuration...
