### ISSUE TITLE
Copy and paste generated code error

### ISSUE THREAD

**Issue by MKiselev** [yiisoft/yii2-gii#277]
### What steps will reproduce the problem?
Generate CRUD, open file, press `ctrl + c`

### What's expected?
When paste into IDE(phpStorm) all be ok.

### What do you get instead?
After paste code was not parsed by IDE. BUT, if select text and paste then all be ok.

### Additional info
Довольно старая бага, опять наткнулся))
Т.е. генерим КРУД, открываем файл и жмём как предложено контрол + ц, не выделяя текст, в результате если вставить из буфера в файл такое, то шторм не понимает что это.
Если выделить, скопировать, вставить, то всё ок.

| Q                | A
| ---------------- | ---
| Operating system | Chrome, Linux, PhpStorm

**Comment by samdark** [comment]
Can't reproduce it w/ PhpStorm, Windows 10, Chrome. What I did:

1. Open Gii model generator.
2. Enter table name.
3. Press "Preview".
4. Click on file name in the list of files to preview (not diff).
5. Press `CTRL`+`C`.
6. Open PhpStorm, create new file, press `CTRL`+`V`.

Works well.

**Comment by MKiselev** [comment]
@samdark I reproduce this trouble on linux and windows systems.

Windows (Model genrator) https://snag.gy/KnrjRf.jpg
Linnux (fixture generator https://github.com/Insolita/yii2-fixturegii ) https://snag.gy/xFdJMZ.jpg

But if I select text and copy all ok.

**Comment by MKiselev** [comment]
Localize trouble, it's chrome bug. In firefox all work ok.

**Comment by MKiselev** [comment]
Not actual for master branch))

https://github.com/yiisoft/yii2-gii/blob/master/assets/gii.js#L81

`replace(/&nbsp;/ig, ' ')` resolve this problem.
