### ISSUE TITLE
Generete relations 1:1 in _form with selecbox

### ISSUE THREAD

**Issue by lukBarros** [yiisoft/yii2-gii#28]
Generete relations 1:1 in _form with selecbox any place input text type.

**Comment by cebe** [comment]
can you explain a bit more, I do not get what you want?

**Comment by lukBarros** [comment]
Using gii, to generate a CRUD where the base model has a 1: 1 in your ER model, then in view _form.php is generated for this relationship a simple type input text field.

I would like to generate shaped selecbox (combobox), style a check box to permitendo only 1 option.

In some experiments I managed to reproduce the desired comporamento during generation.

What do you think of this improvement?

**Comment by samdark** [comment]
It's OK when there aren't many records in the table you're selecting from but it won't work if there are 100s of records. In this case you need autocomplete.

**Comment by lukBarros** [comment]
But DO NOT HAVE FOR A Standard Application, one mapperd active record field or not of autocomplete ? Have?

I know we have when we loaded the JUI .... But it is not loaded by default on a new installation Yii 2 .

@samdark  what way?

**Comment by samdark** [comment]
That's why we aren't providing any generated code for it. There's no solution which is universal and will work for all possible cases. Developer have to modify it anyway.

Since there's an ability to use your own templates, I'm closing the issue.
