### ISSUE TITLE
Install via Composer Seems broken

### ISSUE THREAD

**Issue by comeUpWithItLater** [yiisoft/yii2-gii#284]
Seems broken!

### What steps will reproduce the problem?

```bash 
composer self-update && compose  require --dev --prefer-dist yiisoft/yii2-gii 
```
produce:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yiisoft/yii2-gii 2.0.5 requires bower-asset/typeahead.js 0.10.* | ~0.11.0 -> no matching package found.
    - yiisoft/yii2-gii 2.0.4 requires bower-asset/typeahead.js 0.10.* -> no matching package found.
    - yiisoft/yii2-gii 2.0.3 requires bower-asset/typeahead.js 0.10.* -> no matching package found.
    - yiisoft/yii2-gii 2.0.2 requires bower-asset/typeahead.js 0.10.* -> no matching package found.
    - yiisoft/yii2-gii 2.0.1 requires bower-asset/typeahead.js 0.10.* -> no matching package found.
    - yiisoft/yii2-gii 2.0.0 requires bower-asset/typeahead.js 0.10.* -> no matching package found.
    - Installation request for yiisoft/yii2-gii ^2.0 -> satisfiable by yiisoft/yii2-gii[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |   2.0.11.2 
| PHP version      |  
```
php -v
```
PHP 7.1.3 (cli) (built: Mar 17 2017 22:28:12) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.3, Copyright (c) 1999-2017, by Zend Technologies

| Operating system |
```
uname -a
```
Linux 79be89c4bcfb 4.9.31-moby #1 SMP Sat Jun 24 06:29:23 UTC 2017 x86_64 Linux   <- Alpine

### More Additional info
runing on a docker container : https://github.com/ngineered/nginx-php-fpm

**Comment by cebe** [comment]
try adding `--update-with-dependencies` flag to the `composer require` command. This will ensure dependent packages to be updated, which is not allowed by default.

**Comment by samdark** [comment]
Just tried it:

1. Fresh install of basic app.
2. `composer self-update && composer  require --dev --prefer-dist yiisoft/yii2-gii`.

Went just fine.

**Comment by comeUpWithItLater** [comment]
Fresh install of basic app  and   FXP composer plugin  works .
thank you   @samdark

**Comment by wirwolf** [comment]
I fixed this error in fork. 
https://github.com/MinexSystems/yii2-gii/commit/0cf61f90b6d2894f29c5dd53e31b8f1c6b6d5b81
add this block to composer.
```
"repositories": [
		{
			"type": "vcs",
			"url": "https://github.com/MinexSystems/yii2-gii.git"
		}
	]
```

**Comment by schmunk42** [comment]
This might also happen, when a `bower-asset` would be downgraded, but it is not found by CAP, due to [package optimization](https://github.com/fxpio/composer-asset-plugin/blob/master/Resources/doc/index.md#disable-the-import-filter-using-the-installed-packages), you can try setting this to `false`.
