### ISSUE TITLE
Small suggestion: Option to singularize class names

### ISSUE THREAD

**Issue by Sarke** [yiisoft/yii2-gii#292]
I prefer to have all class names as singular since each object is one item.  I think this is quite common as well.

Unfortunately, db tables sometimes tend to be plural, since they are a collection of several.

Renaming these manually after using Gii is a bit of a pain because of all the relations, query classes, and such.

**Comment by samdark** [comment]
Makes sense.

**Comment by alexkart** [comment]
Hello, is this feature request is still relevant?

**Comment by samdark** [comment]
It is. Yes, feel free to work on it.
