### ISSUE TITLE
Twitter Typeahead repo is stale

### ISSUE THREAD

**Issue by Alex-Code** [yiisoft/yii2-gii#307]
The Twitter typeahead repo hasn't been updated in years.
Might be worth considering using a maintained fork?

https://github.com/corejavascript/typeahead.js

**Comment by schmunk42** [comment]
It's also worth about thinking to drop that requirement completely.
There should be a solution for client-side packages, but moving this one out of Gii (core) seems also reasonable.

@klimov-paul Proposed an idea with templates for the Gii Web UI, which could depend on JSlibs.

**Comment by samdark** [comment]
Will be solved by #390
