### ISSUE TITLE
Move findModel() function before actions in CRUD template

### ISSUE THREAD

**Issue by WadeShuler** [yiisoft/yii2-gii#308]
This isn't really a bug or problem. However, logically, since other actions use `findModel()` (ie: Update/View), then it should be listed first. `findModel()` is basically required for the route actions (index, view, update, create), and therefore should be listed prior to the actions.

I propose that the `findModel()` function should be after the `behaviors()` function and before the CRUD generated action functions (index, view, update, create). It currently is at the very end.

### What steps will reproduce the problem?
Generate CRUD with Gii
look at the generated Controller file. `findModel()` is at the very end, where it doesn't belong based on logic.

### What is the expected result?
`findModel()` should be listed before the route actions, but after `behaviors()`.

### What do you get instead?
`findModel()` is at the end of the file, after the route actions.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.*
| PHP version      | Any
| Operating system | Any

**Comment by rob006** [comment]
> However, logically, since other actions use findModel() (ie: Update/View), then it should be listed first.

I would say that is quite the opposite...

There is already another convention to put private/protected methods after public ones.

**Comment by samdark** [comment]
Won't change it since technically it doesn't matter and it's known that sorting like that isn't regulated by any standard because almost noone would follow it. If you're writing your code by hand requiring certain order would be way too irritating.

**Comment by NLeone** [comment]
First of all, sorry for coming back in this thread, but I do not find issues about my query.

It is not "INSECURE" to use the findOne method ($ id) in findModel without a matrix to clarify which column the search should refer to?

Please forgive my ignorance, but in the documentation it says the following:

"// yii \ web \ Controller ensures that $ id is scalar
public function actionView ($ id)
{
    $ model = Post :: findOne ($ id);
    // ...
}

// explicitly specifying the column to search, passing to scalar or array here will always result in finding a single record
$ model = Post :: findOne (['id' => Yii :: $ app-> request-> get ('id')]);

// do NOT use the following code! it is possible to inject an array condition to filter by arbitrary column values!
$ model = Post :: findOne (Yii :: $ app-> request-> get ('id')); "

So I think we should not correct this action?

Thank you very much and forgive again for the intromission.

Greetings to all!

**Comment by uldisn** [comment]
This problem simple solve in findModel() adding variable type to $id or/and add field types in action functions

` protected function findModel(int $id)
 {
 }`

**Comment by NLeone** [comment]
@uldisn look this please:

![41210610_10156545959454098_4643486020711481344_n](https://user-images.githubusercontent.com/964781/45179090-dabd3a80-b1ed-11e8-8e2d-52e18267ecd4.jpg)

There you see that it makes good validations to protect the query, what do you think?

**Comment by uldisn** [comment]
Yes, is protected.
