### ISSUE TITLE
ActiveQuery missing parameter when instancied

### ISSUE THREAD

**Issue by gwelr** [yiisoft/yii2-gii#316]
In a new project, my code was strictly generated by GII, using only one controller.

In actionIndex, the first line is: 

```php
        $searchModel = new ConsultantQuery();
```
New ConsultantQuery was generated by GII as extending ActiveQuery (no change on my side). 

When calling index.php?r=consultant/index , the following error occurs: 
```php
 PHP Warning – yii\base\ErrorException
Missing argument 1 for yii\db\ActiveQuery::__construct(), called in /var/www/basic/controllers/ConsultantController.php on line 38 and defined
```
Because the constructor of ActiveQuery is defined as:
```php 
    /**
     * Constructor.
     * @param string $modelClass the model class associated with this query
     * @param array $config configurations to be applied to the newly created query object
     */
    public function __construct($modelClass, $config = [])
```

I don't get what is going wrong here (except that $modelClass is not provided to ActiveQuery constructor). 

### What steps will reproduce the problem?
* Create a new project (with the basic template) with one model
* from GII generate Model, CRUD and Controller file
* go to the index view of the  controller 

### What's expected?
```php
        $searchModel = new ConsultantQuery();
``` 
should work fine.
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13.1
| PHP version      | 7.0
| Operating system | Ubuntu
|Gii version | 2.0.5

**Comment by samdark** [comment]
It should not. Either provide model name or use `Consultant::find()` to obtain the query instead.

**Comment by gwelr** [comment]
I agree with you it should not but this is straight, out-of-the-box code generated by GII. Shouldn't GII call `Consultant::find()` instead of 'new ConsultantQuery()`. 

In other words, why is GII issuing code that does not even comply with the ActiveQuery constructor? Is it on purpose? Because if it is, I don't get the why.

**Comment by eisdevelopers** [comment]
I am facing the same issue.
Has someone found any work around

**Comment by berosoboy** [comment]
I think you guys are providing an `ActiveQuery`, rather than an `ActiveRecord` class in the **"Search Model Class"** field in the CRUD Generator form.

**Comment by mnhvandz** [comment]
Same here!, when  ActiveQuery
