### ISSUE TITLE
Exception in Module generator with php7.2

### ISSUE THREAD

**Issue by igribov** [yiisoft/yii2-gii#318]
### What steps will reproduce the problem?
When I try to generate a new module in gii (using php7.2), it throws Exception 
### What's expected?
New module
### What do you get instead?
Exception Cannot use yii\base\Object as Object because 'Object' is a special class name

### How to fix it
In file /yiisoft/yii2-gii/CodeFile.php
1) `use yii\base\Object;` to `use yii\base\BaseObject;`
2) `class CodeFile extends Object` ---> `class CodeFile extends BaseObject`

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13.1
| PHP version      | 7.2
| Operating system | macOS

**Comment by schmunk42** [comment]
I think this is expected at the moment ... there's a [2.1 branch](https://github.com/yiisoft/yii2-gii/tree/2.1) which supports PHP 7.2 AFAIK.

@yiisoft/core-developers How about adding a constraint to the 2.0.x branch which excludes PHP 7.2 - though composer might fall back to an older version when installing on PHP 7.2.

**Comment by samdark** [comment]
No, it's not expected. Should be fixed.
