### ISSUE TITLE
Generate a base file for models

### ISSUE THREAD

**Issue by thiagotalma** [yiisoft/yii2-gii#32]
Hello everybody,

Now that the Gii has its own home, I would like to take a subject that has been discussed [here](https://github.com/yiisoft/yii2/issues/102) but the topic died.

The idea of having an ever synchronized file with the database is very interesting. Some mods of gii (the old [Giix](http://www.yiiframework.com/extension/giix/) from @rcoelho and [Giiant](https://github.com/schmunk42/yii2-giiant), from @schmunk42, for example) implement this idea. Ever since I started working in Yii have my gii modified to generate this base file.

It makes it much easier to keep the model always synchronized with the database. In the data model file override only those methods that are needed, usually adding rules or correcting labels.

The only "problem" I see this to be officially implemented is the question of performance, as it will add an inheritance.

I ask the experts: the loss of performance is really relevant?

Having this functionality as an option in Gii would be helpful?

Hugs!

**Comment by cebe** [comment]
> I ask the experts: the loss of performance is really relevant?

I do not think it is relevant, if you want to use this feature, you can do it, if not just skipt it.

> Having this functionality as an option in Gii would be helpful?

IMO gii generated code is and can only be a template which needs adjustments, and not only by extending the generated class. There are auto generated relation names which may not match your needs, the rules are just a basic set guessed from which in no case ever match the real rules needed in the app if you take it seriously.

If you adjust a table in the DB you can use the gii preview to display the model code and copy the parts that are relevant over to your editor. You may even use "Compare with Clipboard" in PHPstorm to merge the details. I do not think autogenerated, unadjusted code has a valid use case.

**Comment by thiagotalma** [comment]
@cebe Do not you think valid leave open discussion to listen other opinions and suggestions from the community?

Okay. Let's start from the assumption that we will not have an unalterable file.

When we have a very altered class, the display of the difference results in a large colorful mess.

It would be good that the Yii2 help us compare with the version "original" before the last change so we can view and copy only what has really changed in the database. What do you think?

**Comment by cebe** [comment]
we have discussed this many times before (found only https://github.com/yiisoft/yii2-gii/issues/15 but I am sure there were more) and you can even use it this way, not sure what gii must implement for this btw.

as far as I see, the diff view of gii and preview feature already have all you need...

**Comment by samdark** [comment]
Isn't it doing it already? Gii takes current file contents and compares it with what will be generated so it's exactly "original before last change".

**Comment by thiagotalma** [comment]
@samdark, what I meant is to show the difference generated ONLY by changing the database, ignoring any changes made by the developer.

As if it were made a snapshot every change in the database and the comparison made with the snapshot, instead of comparing with the "real" file, as modified by the developer.

This snapshot replace the "base file", simulating a never changed file.
