### ISSUE TITLE
Draft new release

### ISSUE THREAD

**Issue by schmunk42** [yiisoft/yii2-gii#323]
### What steps will reproduce the problem?

Try to update code to `BaseObject`, like in https://github.com/schmunk42/yii2-giiant/pull/220#issuecomment-353606949

### What's expected?

Easy upgrading with requiring stable tags

### What do you get instead?

Can't upgrade since libs can not depend on `dev-master` with stability stable.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2-gii/milestones/2.0.6

**Comment by samdark** [comment]
Need to check these. Then will do release.

**Comment by samdark** [comment]
Done.
