### ISSUE TITLE
Issue with composer --no-dev

### ISSUE THREAD

**Issue by spongeb00b** [yiisoft/yii2-gii#326]
### What steps will reproduce the problem?
perform a composer install for staging or prod environment (using --no-dev directive) in my case:

`composer install --no-ansi --no-interaction --no-progress --no-scripts --optimize-autoloader --no-dev`

my composer.json:
```
{
  "name": "digisin/plurima-gestionale",
  "description": "Gestionale commesse per Plurima",
  "keywords": ["yii2"],
  "homepage": "http://digisin.it/",
  "type": "project",
  "license": "EULA",
  "support": {
    "issues": "...",
    "wiki": "...",
    "source": "..."
  },
  "minimum-stability": "stable",
  "repositories": [
    {
      "type": "vcs",
      "url": "git@git.digisin.net:digisin/yii2-softdelete.git"
    }
  ],
  "require": {
    "php": ">=5.4.0",
    "yiisoft/yii2": "~2.0.5",
    "yiisoft/yii2-bootstrap": "~2.0.0",
    "yiisoft/yii2-swiftmailer": "~2.0.0",
    "yiisoft/yii2-redis": "~2.0.0",
    "kartik-v/yii2-widgets": "~3.4.0",
    "yiisoft/yii2-twig": "~2.0.0",
    "yii2tech/ar-role": "~1.0.2",
    "yii2mod/yii2-enum": "1.7",
    "digisin/yii2-softdelete": "^1.1",
    "yii2mod/yii2-settings": "~2.2",
    "kartik-v/yii2-money": "dev-master",
    "kartik-v/yii2-grid": "3.1.1",
    "kartik-v/yii2-mpdf": "*",
    "yiisoft/yii2-jui": "~2.0.0",
    "mikehaertl/php-pdftk": "~0.4.0",
    "symfony/yaml": "~3.3.2",
    "bower-asset/jquery": "2.2.*@stable",
    "bower-asset/gentelella": "dev-master",
    "bower-asset/bootstrap-sass-official": "~3.3.6",
    "bower-asset/fontawesome": "~4.3.0",
    "bower-asset/fastclick": "~1.0.6",
    "bower-asset/nprogress": "~0.2.0",
    "bower-asset/moment/moment": "~2.17.1",
    "bower-asset/eonasdan-bootstrap-datetimepicker": "^4.17.45",
    "bower-asset/fronteed/iCheck": "~1.0.2",
    "bower-asset/enyo/dropzone": "~4.3.0", 
    "bower-asset/minddust/bootstrap-progressbar": "~0.9.0",
    "beaten-sect0r/yii2-db-manager": "*"
  },
  
  "require-dev": {
    "yiisoft/yii2-debug": "~2.0.0",
    "yiisoft/yii2-gii": "~2.0.0",
    "yiisoft/yii2-faker": "~2.0.0",
    "yiisoft/yii2-apidoc": "~2.0.0",
    
    "codeception/base": "^2.2.3",
    "codeception/verify": "~0.3.1",
    "codeception/specify": "~0.4.3"
  },
  "config": {
    "process-timeout": 1800
  },
  "scripts": {
    "post-create-project-cmd": [
      "yii\\composer\\Installer::postCreateProject"
    ]
  },
  "extra": {
    "yii\\composer\\Installer::postCreateProject": {
      "setPermission": [
        {
          "runtime": "0777",
          "web/assets": "0777",
          "yii": "0755"
        }
      ],
      "generateCookieValidationKey": [
        "config/web.php"
      ]
    },
    "asset-installer-paths": {
      "npm-asset-library": "vendor/npm",
      "bower-asset-library": "vendor/bower"
    }
  }
}
```

### What's expected?
Normal composer behavior installing all dependencies

### What do you get instead?
Problem 1
    - yiisoft/yii2-gii 2.0.6 requires phpspec/php-diff >=1.0.2 -> satisfiable by phpspec/php-diff[dev-master, 1.0.x-dev] but these conflict with your requirements or minimum-stability.
    - yiisoft/yii2-gii 2.0.5 requires phpspec/php-diff >=1.0.2 -> satisfiable by phpspec/php-diff[dev-master, 1.0.x-dev] but these conflict with your requirements or minimum-stability.
    - yiisoft/yii2-gii 2.0.4 requires phpspec/php-diff >=1.0.2 -> satisfiable by phpspec/php-diff[dev-master, 1.0.x-dev] but these conflict with your requirements or minimum-stability.
    - yiisoft/yii2-gii 2.0.3 requires phpspec/php-diff >=1.0.2 -> satisfiable by phpspec/php-diff[dev-master, 1.0.x-dev] but these conflict with your requirements or minimum-stability.
    - yiisoft/yii2-gii 2.0.2 requires phpspec/php-diff >=1.0.2 -> satisfiable by phpspec/php-diff[dev-master, 1.0.x-dev] but these conflict with your requirements or minimum-stability.
    - yiisoft/yii2-gii 2.0.1 requires phpspec/php-diff >=1.0.2 -> satisfiable by phpspec/php-diff[dev-master, 1.0.x-dev] but these conflict with your requirements or minimum-stability.
    - yiisoft/yii2-gii 2.0.0 requires phpspec/php-diff >=1.0.2 -> satisfiable by phpspec/php-diff[dev-master, 1.0.x-dev] but these conflict with your requirements or minimum-stability.
    - Installation request for yiisoft/yii2-gii ~2.0.0 -> satisfiable by yiisoft/yii2-gii[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6].

Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |2.0.13.1
| PHP version      |5.6.30-0+deb8u1
| Operating system |Debian GNU/Linux 8 (jessie)

**Comment by samdark** [comment]
Already fixed. There was an issue at packagist.org.

**Comment by spongeb00b** [comment]
@samdark Thank you very much! It works now :D
