### ISSUE TITLE
Cannot instantiate abstract class common\models\AbstractActiveRecord

### ISSUE THREAD

**Issue by achretien** [yiisoft/yii2-gii#327]
### What steps will reproduce the problem?
Use an abstract class as $baseClass

### What's expected?
Generate the files properly.

### What do you get instead?
The error "Cannot instantiate abstract class common\models\AbstractActiveRecord" in `generators/model/Generator.php` at line 686.

https://github.com/yiisoft/yii2-gii/blob/f15b8dce4ef577c250112cf06b4616cbb2aca4ea/generators/model/Generator.php#L686

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13.1
| PHP version      | 7.1
| Operating system | alpine-linux

**Comment by NickvdMeij** [comment]
Same problem here after updating to dev-master from v2.0.5

Yii version: 2.0.15.1
PHP version: 7.0.26
Operation System: Debian
