### ISSUE TITLE
BC ISSUE with Yii 2.0.14. Release a new version for model GENERATOR on TINYINT  (line 318)

### ISSUE THREAD

**Issue by sebathi** [yiisoft/yii2-gii#338]
BUG: After Yii 2.0.14 release 
When I recreate my models using gii, all the rules for tinyint(1) on mysql change from integer to string(1). That makes the use of booleans unusable.

This is fixed on this repository but not release has been done.

Change composer requirement for Yii2 to 2.0.14+

**Comment by sebathi** [comment]
Every time that we make changes on our database we need to review that this file is not broken with our Yii2 version.  

This should be released IMHO as a new version (2.0.6.1??) and then add new enhancements. Right now this is breaking things on our Yii2 applications every day.

**Comment by samdark** [comment]
The fix is in master already.

**Comment by sebathi** [comment]
But that makes me use composer with Dev and not with stable. :(

**Comment by samdark** [comment]
Yes, we'll release it. Just not right now.

**Comment by schmunk42** [comment]
@sebathi You can pin a dependency via its commit hash in your project's `composer.json`

    dev-master#abcdef1234

So you do not upgrade all the time

**Comment by sebathi** [comment]
Thanks!!
