### ISSUE TITLE
Trying to get property of non-object  [in ...vendor\yiisoft\yii2-gii\generators\model\Generator.php at line 511]

### ISSUE THREAD

**Issue by Lordfef** [yiisoft/yii2-gii#34]
Hi all, i'm getting this error when i try to generate new Model.
I see that if i uncheck " Generate Relations" (default checked) it works, but i need to create manually relation of my table /foreign keys

I try to delete yii2-gii directory and re-launch composer but i have the same issue.

There are many weeks that i don't use gii because i deploy different section my project, but i'm sure that when i used it at the beginning of my project "Generate Relations" works fine.

**Comment by samdark** [comment]
Need more info:

1. Which database you're using? MySQL? PostgreSQL? Other?
2. What is the schema you're trying to generate relations for? Could you provide it?
3. What exactly you're entering in form fields?

**Comment by rtwent** [comment]
Hi. I have the same issue when try to generate model with "Generate Relations" checked. Without checking it, everything seems fine.

1. DB engine is MySQL
2. Create code is:
CREATE TABLE `systemstatuses` (
	`systemstatuses_id` TINYINT(4) UNSIGNED NOT NULL AUTO_INCREMENT,
	`systemstatuses_name` VARCHAR(50) NOT NULL,
	`systemstatuses_logo` VARCHAR(50) NULL DEFAULT NULL,
	`systemstatuses_desc` VARCHAR(255) NULL DEFAULT NULL COMMENT 'desc',
	`systemstatuses_days` SMALLINT(6) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'days',
	`systemstatuses_price` INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'price',
	PRIMARY KEY (`systemstatuses_id`),
	UNIQUE INDEX `systemstatuses_id` (`systemstatuses_id`),
	UNIQUE INDEX `systemstatuses_name` (`systemstatuses_name`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

I have such issue with every table of my database. Pitty, but I cann't tell You the time when it is appeared.

**Comment by rtwent** [comment]
More info about exception in http://koplion.com/images/exc.png

**Comment by cebe** [comment]
unable to reproduce...

![bildschirmfoto am 2015-05-08 um 00 25 40](https://cloud.githubusercontent.com/assets/189796/7527141/cd333a80-f518-11e4-8a71-1a72d8efe5b8.png)

same result with and without generating relations...

**Comment by rtwent** [comment]
I'll check tonight (I have no connection to the project). I have one table that started with "_", maybe 2camelCase is not working for such foolish decision. Try to create this table in the same database as "systemstatuses" and check it out (create model for "systemstatuses"). 

<code>
CREATE TABLE `_crawl_clients` (
	`id` SMALLINT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(100) NOT NULL,
	`controller` VARCHAR(50) NOT NULL COMMENT 'controller to work',
	PRIMARY KEY (`id`),
	UNIQUE INDEX `id` (`id`),
	UNIQUE INDEX `name` (`name`),
	UNIQUE INDEX `controller` (`controller`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=7
AVG_ROW_LENGTH=2730
;</code>

If everything will be OK again, I'll try to undestand what is wrong with my environment.

**Comment by rtwent** [comment]
Look, I reproduce it.
<strong>Legend:</strong> I installed anmah user (https://github.com/amnah/yii2-user) first time in February (on 2015-05-07 was the last update). The out of box DB schema is here: https://github.com/amnah/yii2-user/blob/master/migrations/m150214_044831_init_user.php
"Out of box" main table name is "user".
<strong>Disco time:</strong>
Code from the dump below will throw an error "Trying to get property of non-object":
<code>
SET FOREIGN_KEY_CHECKS=0;
DROP DATABASE IF EXISTS `yii2test`;
CREATE DATABASE `yii2test`
    CHARACTER SET 'utf8'
    COLLATE 'utf8_general_ci';
USE `yii2test`;

CREATE TABLE `systemstatuses` (
  `systemstatuses_id` TINYINT(4) UNSIGNED NOT NULL AUTO_INCREMENT,
  `systemstatuses_name` VARCHAR(50) COLLATE utf8_general_ci NOT NULL,
  `systemstatuses_logo` VARCHAR(50) COLLATE utf8_general_ci DEFAULT NULL,
  `systemstatuses_desc` VARCHAR(255) COLLATE utf8_general_ci DEFAULT NULL COMMENT 'desc',
  `systemstatuses_days` SMALLINT(6) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'days',
  `systemstatuses_price` INTEGER(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'price',
  PRIMARY KEY (`systemstatuses_id`),
  UNIQUE KEY `systemstatuses_id` (`systemstatuses_id`),
  UNIQUE KEY `systemstatuses_name` (`systemstatuses_name`)
)ENGINE=InnoDB
AUTO_INCREMENT=1 CHARACTER SET 'utf8' COLLATE 'utf8_general_ci'
COMMENT=''
;
CREATE TABLE `user` (
  `id` INTEGER(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
)ENGINE=InnoDB
AUTO_INCREMENT=34 CHARACTER SET 'utf8' COLLATE 'utf8_general_ci'
COMMENT=''
;
</code>

<i>While code from the dump below, will give me expected results:</i>
<code>
SET FOREIGN_KEY_CHECKS=0;
DROP DATABASE IF EXISTS `yii2test`;
CREATE DATABASE `yii2test`
    CHARACTER SET 'utf8'
    COLLATE 'utf8_general_ci';
USE `yii2test`;
CREATE TABLE `systemstatuses` (
  `systemstatuses_id` TINYINT(4) UNSIGNED NOT NULL AUTO_INCREMENT,
  `systemstatuses_name` VARCHAR(50) COLLATE utf8_general_ci NOT NULL,
  `systemstatuses_logo` VARCHAR(50) COLLATE utf8_general_ci DEFAULT NULL,
  `systemstatuses_desc` VARCHAR(255) COLLATE utf8_general_ci DEFAULT NULL COMMENT 'desc',
  `systemstatuses_days` SMALLINT(6) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'days',
  `systemstatuses_price` INTEGER(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'price',
  PRIMARY KEY (`systemstatuses_id`),
  UNIQUE KEY `systemstatuses_id` (`systemstatuses_id`),
  UNIQUE KEY `systemstatuses_name` (`systemstatuses_name`)
)ENGINE=InnoDB
AUTO_INCREMENT=1 CHARACTER SET 'utf8' COLLATE 'utf8_general_ci'
COMMENT=''
;
CREATE TABLE `user2` (
  `id` INTEGER(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
)ENGINE=InnoDB
AUTO_INCREMENT=34 CHARACTER SET 'utf8' COLLATE 'utf8_general_ci'
COMMENT=''
;
</code>
<strong>The main difference of this dumps, is the name of the table: "user".</strong>
When the name is user2 everything is OK, but the name "user" will throw an error. "user" does not belongs to reserved words (http://dev.mysql.com/doc/refman/5.6/en/reserved-words.html, https://mariadb.com/kb/en/mariadb/reserved-words/).

Best regards, and thank You for Your work.

**Comment by h2ooooooo** [comment]
I had this issue when importing a specific table from another database. The dump of the table included a foreign key that was also copied over, but the foreign key table did not exist in the new database. The solution was to simply delete the foreign key pointing to a non-existent table.

**Comment by rommcr** [comment]
I have same error. It appears when option "Generate Relations" is checked. The reason in incorrect relations in field comments. Check all "ADD CONSTRAINT FOREIGN KEY ... " in your table definitions.

**Comment by cloudswitch** [comment]
I have same error. FK to table user/id (basic user table from the advanced template). Without relations it works, with relations it doesn't work.

**Comment by jusernt** [comment]
It happened the same thing when I was active "Generate Relations" throwing an error, install the "mdmsoft / yii2-admin" and "dektrium / yii2-user" packages.

The problem was that when migrating tables "mdmsoft / yii2-admin" only migrated two missing one. The three tables were related: auth_rule, auth_item, auth_item_child (missing).

Remove the tables and run GII

**Comment by marojahan** [comment]
I have the same error, any update on this issue?

**Comment by Formcd** [comment]
Same error with user's table...

**Comment by osCMattiFinn** [comment]
I get the same error.  I suspect the problem is that if "Generate Relations" is checked and the table does not have any relations it throws the error (will test).

It's definitey a bug.

**Comment by masterGH** [comment]
Exactly the same issue as above, with a brand new database (no data), but mine is when I try to create a model for a self-joined table.  If I add the self-join in the MySQL database (through MySQL Workbench), and then try to create the model through Gii, it throws the error.  If I remove the self-join and try to create the model through Gii, it works fine.

**Comment by samdark** [comment]
@masterGH please provide SQL to create such table. Thanks.

**Comment by masterGH** [comment]
CREATE TABLE IF NOT EXISTS `xyzcompany`.`corporation` (
  `id` INT(10) UNSIGNED NOT NULL,
  `master_corporation_id` INT(10) UNSIGNED NOT NULL,
  `name` VARCHAR(125) NOT NULL,
  `federal_employer_identification_number` VARCHAR(25) NOT NULL,
  `type` ENUM('master', 'sub') NOT NULL,
  PRIMARY KEY (`id`, `master_corporation_id`),
  UNIQUE INDEX `federal_employer_identification_number_uidx` (`federal_employer_identification_number` ASC),
  CONSTRAINT `fk_corporation_corporation`
    FOREIGN KEY (`id`)
    REFERENCES `xyzcompany`.`corporation` (`master_corporation_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

**Comment by masterGH** [comment]
@samdark I have also tried it without making the master_corporation_id part of the primary key, as such:

CREATE TABLE IF NOT EXISTS `xyz_app`.`corporation` (
  `id` INT(10) UNSIGNED NOT NULL,
  `master_corporation_id` INT(10) UNSIGNED NOT NULL,
  `federal_employer_identification_number` VARCHAR(25) NOT NULL,
  `name` VARCHAR(125) NOT NULL,
  `type` ENUM('master', 'sub') NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `federal_employer_identification_number_uidx` (`federal_employer_identification_number` ASC),
  INDEX `fk_corporation_master_corporation_idx` (`master_corporation_id` ASC),
  CONSTRAINT `fk_corporation_master_corporation_id`
    FOREIGN KEY (`master_corporation_id`)
    REFERENCES `xyz_app`.`corporation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

**Comment by masterGH** [comment]
Just an update.  Gii is now completely broken after update 2.06.  I cannot add any new models.  I get the same error as before, "Trying to get property of non-object" no matter what model I try to add (unless I uncheck 'Generate Relations')...but I've even tried adding models that have NO relationships at all.  I have uninstalled gii and reinstalled it as well to no avail.

**Comment by rtwent** [comment]
@masterGH I had the same issue, see comment https://github.com/yiisoft/yii2-gii/issues/34#issuecomment-100293133 Try to check you DB for broken FK. In mysql Workbench I tryied to create the model of my whole DB (DATABASE-REVERSE ENGINEER-etc...) - and it showed me broken FK. After fixing it, everything works fine. I am not sure, that it will fix You problem.

**Comment by masterGH** [comment]
@rtwent @samdark I'm pretty sure my issue is caused by my own lack of understanding of the self-join, so I'm reevaluating the issue.  I did reverse engineer the database into Workbench but it didn't produce any disconnected FK's.  I will keep an eye out for that issue going forward though as it seems the relationships are quite delicate between Workbench, the MySQL db and the Yii models and the workflow can be quite tricky to get correct.  Thanks for the advice!

**Comment by Faryshta** [comment]
@masterGH can you provide your FULL schema? at some point the generateRelations() method invokes every table in your schema trying to find one that is related to your table with a foreign key pointing at the table you are modeling.

example if you have a table product and one product_category. When you produce the model for product_category the method checks the table product to see if there is a foreign key there pointing to product_category.

**Comment by masterGH** [comment]
@Faryshta I am rebuilding the project from scratch with a new installation as I could not get Gii to come back online after the posted issue, though I don't think it was a problem with Yii, so much as my lack of understanding about what you described above where the method invokes every table trying to find a key.  I should have probably been checking the models more closely as they were produced by Gii, but alas, I am a Yii rookie.

I'll update this thread should I see the issue reappear.  As for now, I have a fresh installation of Yii2.06 Advanced App and a few models built to re-start my project with and haven't seen the issue reappear though I haven't come to my self-join table yet.

**Comment by Faryshta** [comment]
if you can get the old db schema please share it on pastie.org

**Comment by masterGH** [comment]
@samdark @Faryshta @rtwent Just an update, I've successfully created the self-join table from the earlier project with a better understanding of the whole relationship creation process with Gii and I'm quite certain that it was my lack of experience with it before that created the issue.  Sorry about that.  No errors; all is well.

**Comment by osCMattiFinn** [comment]
Why was this ticket closed?  Just because one person made errors?

This bug still exists on a very ordinary database with nothing special whatsoever like "self joins"

**Comment by samdark** [comment]
@osCMattiFinn it's getting messy. I can't tell which code will reproduce the issue anymore.

**Comment by osCMattiFinn** [comment]
CREATE TABLE IF NOT EXISTS  `accessory` (
 `id` INT( 11 ) UNSIGNED NOT NULL AUTO_INCREMENT ,
 `master_id` INT( 11 ) UNSIGNED NOT NULL ,
 `product_id` INT( 11 ) UNSIGNED NOT NULL ,
 `sort_order` INT( 11 ) UNSIGNED NOT NULL ,
PRIMARY KEY (  `id` ) ,
KEY  `master_id_idx` (  `master_id` ) ,
KEY  `product_id_idx` (  `product_id` )
) ENGINE = INNODB DEFAULT CHARSET = latin1 AUTO_INCREMENT =1

Use Gii to create a model for this table with "Generate Relations" checked.  It will throw the error.

This table has no relations, which I suspect is the problem.

Error thrown:

Trying to get property of non-object

Here:

advanced\vendor\yiisoft\yii2-gii\generators\model\Generator.php

    while (isset($relations[$table->fullName][$name])) {   // here is the probem
        $name = $rawName . ($i++);
    }

**Comment by osCMattiFinn** [comment]
We can see that the above code is just wrong.

**Comment by Faryshta** [comment]
since there is a `key`, then `gii` assumes its a foreign key and invokes the table associated to that key which returns `null` then `$table->fullName` throws Error

**Comment by samdark** [comment]
@osCMattiFinn tried your schema. Not getting any errors while generating model w/ relations.

![qip shot - screen 294](https://cloud.githubusercontent.com/assets/47294/9225813/1865f528-4114-11e5-8177-36829839e92b.png)

**Comment by samdark** [comment]
No issues with @masterGH schema either.

**Comment by cebe** [comment]
[Heisenbug](https://en.wikipedia.org/wiki/Heisenbug) :)

**Comment by samdark** [comment]
Definitely. @osCMattiFinn, @masterGH would be nice if you'll start with fresh advanced app and reproduce the error providing exact schema and actions to do it.

Can't do anything till it's reproduced.

**Comment by osCMattiFinn** [comment]
You cannot see that this code is just wrong?  It will always throw an error if $table->fullName][$name] is not set.

    while (isset($relations[$table->fullName][$name])) {   // here is the probem
        $name = $rawName . ($i++);
    }

**Comment by samdark** [comment]
I need a way to reproduce this case.

**Comment by cebe** [comment]
@osCMattiFinn can you paste the full stack trace of the error?

**Comment by cebe** [comment]
also show the output of `composer -i`, your php version, and the version of MySQL server.

**Comment by vibezzz** [comment]
The problem is when DB has tables with wrong formed foreign keys. First create two relative tables, then drop `old_test`. And then try to generate model for any other valid table with "generate relations" enabled.

```
CREATE TABLE `old_test` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `test` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `old_id` int(10) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_oldtest_id` (`old_id`),
  CONSTRAINT `FK_not_exist` FOREIGN KEY (`old_id`) REFERENCES `old_test` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

**Comment by cebe** [comment]
the code is invoced to check if there are tables that have foreign keys to your table.
Also there is an isset() check around that code so I do not see the problem.

**Comment by cebe** [comment]
@osCMattiFinn still would be really helpful to have a full stacktrace.

**Comment by osCMattiFinn** [comment]
cebe, you cannot use that isset() construct in a while loop like that.  If the object is not set it will always throw an error.

**Comment by cebe** [comment]
@osCMattiFinn still without reproducing we can only guess how to fix it, can you give me a stack trace or not?

**Comment by samdark** [comment]
@vibezzz how did you deleted that table?

```
Query: DROP TABLE `old_test`

Error Code: 1217
Cannot delete or update a parent row: a foreign key constraint fails
```

**Comment by samdark** [comment]
OK. Managed to do that with

```sql
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE `old_test`;
SET FOREIGN_KEY_CHECKS = 1;
```

**Comment by samdark** [comment]
Reproduced.

That's definitely wery broken DB state btw., I'd think about tools you're using. If these are allowing dropping tables and not dropping foreign keys pointing at these at the same time, these tools are kinda broken.

**Comment by samdark** [comment]
Now such situation is handled properly. Thanks everyone for hints.

**Comment by masterGH** [comment]
Let me apologize in advance for the very basic rookie question but to make the updated changes, do I manually just make the changed lines directly into the files with copy/paste/delete or is there some update process that will update the files for me?  In short, how do I update my files to reflect your recent change to the files?  I ran composer update but it didn't find any changes.  Thanks for any help you can provide.

**Comment by samdark** [comment]
In your `composer.json` change `"yiisoft/yii2-gii": "something",` to `"yiisoft/yii2-gii": "@dev",`.

**Comment by masterGH** [comment]
All of you that work on this project are geniuses and it is VERY much appreciated.  @samdark Thank you sir.  Understanding how the update process works has just changed my life.  :)

**Comment by samdark** [comment]
Yep, Composer is very handy when you're using propely.

**Comment by farmani** [comment]
![screen shot 2015-12-01 at 4 07 30 am](https://cloud.githubusercontent.com/assets/1329580/11489049/1917063c-97e1-11e5-8f3d-0f3246a06a56.png)
I think it's still the bug for the table which has relation to themselves I receive exact same error message for either category table or category_has_prodcut
1. in /Users/Server/mall/website/vendor/yiisoft/yii2-gii/generators/model/Generator.php at line 511

**Comment by farmani** [comment]
after updating to @dev Generate Relation has been disabled now :|

**Comment by rtwent** [comment]
100% of reproducing this bug. Foreign keys relations between two databases (too rare case) when in php.ini error_reporting = E_ALL and php version > 5.6

**Comment by farmani** [comment]
I'm not sure about php ver that may impact but yes my php version is also > 5.6

**Comment by samdark** [comment]
@rtwent try master branch. It should be already fixed.

**Comment by farmani** [comment]
@samdark why its disabled relational database?

**Comment by samdark** [comment]
Looks like a separate issue. Could you submit it?

**Comment by farmani** [comment]
sure I will open a new thread

**Comment by samdark** [comment]
Try code from `master` branch.

**Comment by farmani** [comment]
please release a new stable release to prevent this

**Comment by SilverFire** [comment]
@farmani we are going to release 2.0.7 soon

**Comment by Zerebokep** [comment]
After updating to 2.0.7 I get the same error with every table which contains a foreign key. Had no problems with 2.0.6.

`
while (isset($relations[$table->fullName][$name])) {
            $name = $rawName . ($i++);
        }
`

Tables are created with MySQLWorkbench. Using PHP 5.6. Mysql 5.5
