### ISSUE TITLE
gii generate CRUD error for (mysql) tinyint

### ISSUE THREAD

**Issue by JeanWolf** [yiisoft/yii2-gii#340]
### What steps will reproduce the problem?

gii generate CRUD for some Model, that has  tinyint column (mysql)

### What's expected?

  `integer` in rules return, and filter as ` 'some_attr' => $this->some_attr`

### What do you get instead?

`safe` in rules return,  filter like  `['like', 'some_attr', $this->some_attr]`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.14
| PHP version      | 7.2.2
| Operating system | MacOS 10.12.6

should update  function `generateSearchRules` and `generateSearchConditions` in file `generators/crud/Generator.php` 
at about line 338 and 432
```
                case Schema::TYPE_TINYINT: //add this case

//...
```
then things goes right

**Comment by samdark** [comment]
Already fixed in master.

**Comment by JeanWolf** [comment]
Uh-huh? This issue is for generator CRUD  not  Model, seems unfixed yet  in the master branch. Please recheck `yii2-gii/src/generators/crud/Generator.php`

**Comment by samdark** [comment]
Please submit a pull request.
