### ISSUE TITLE
Gii 2.0.6 model\Generator tinyint rule as string, fixed in 2.1

### ISSUE THREAD

**Issue by jkovacs618** [yiisoft/yii2-gii#350]
Found that Gii 2.0.6 yii\gii\generators\model\Generator.php creates rules for tinyint as 'string' instead of 'integer'.  Found that yii\db\Schema.php introduced constant of TYPE_TINYINT and others, which is not checked in Gii 2.0.6+, so fallback type for tinyint is 'string' and causes AR model save errors. Was using a minimum-stability of "RC" so could not get Gii 2.1 with the fix for TYPE_TINYINT.  Forced to use "yiisoft/yii2-gii" version of "dev-master" to get Gii 2.1 to get the fix to avoid AR model incorrect rules.

Request: Consider patching Gii 2.0.6+ to support the new Schema TYPE constants to produce 'integer' rules instead of 'string' to avoid breakage in models, until Gii 2.1 is ready and tagged for RC stability.

### What steps will reproduce the problem?
composer.json:
```
"minimum-stability": "RC",
"require": { "yiisoft/yii2": "2.0.*", ... },
"require-dev": { "yiisoft/yii2-gii": "2.0.*", ... },
```
DB table column:
`deleted` tinyint(1) unsigned NOT NULL DEFAULT '0',
### What is the expected result?
Composer installation of yiisoft/yii2-gii 2.0.6
Correct AR model rule: [['deleted'], 'integer'],
Result: AR model save of deleted=1 should succeed without error.
### What do you get instead?
Incorrect AR model rule: [['deleted'], 'string', 'max' => 1],
Result: On AR model save:
Model Errors: deleted: Deleted must be a string., Value: integer 1.

OR

### What steps will reproduce the problem?
composer.json:
```
"minimum-stability": "RC",
"require": { "yiisoft/yii2": "2.0.*", ... },
"require-dev": { "yiisoft/yii2-gii": "~2.1.0", ... },
```
### What is the expected result?
Composer installation of yiisoft/yii2-gii 2.1
### What do you get instead?
Problem 1: The requested package yiisoft/yii2-gii ~2.1.0 is satisfiable by yiisoft/yii2-gii[2.1.x-dev] but these conflict with your requirements or minimum-stability.

### Additional info
| Yii version      | 2.0.15.1
| PHP version      | 7.2.2
| Operating system | Ubuntu 16.04

**Comment by samdark** [comment]
Fixed in 2.0.7, it will be released for 2.0.x.
