### ISSUE TITLE
Mysql JSON fields are validated by string validator, which throws error on save

### ISSUE THREAD

**Issue by yavuzg2** [yiisoft/yii2-gii#351]
### What steps will reproduce the problem?
1. Define a json column in a mysql table.
2. Generate the model and crud files.
3. Fill the JSON column for a row with valid json data in the database.
4. Remove the json field from crud form.
5. Execute $model->save() on the row without changing the json column.

### What's expected?
Add the safe validator instead of string validator, or define a custom validator for json data

### What do you get instead?
Gii adds a string validator for json columns which throws an error while validating, e.g. catalog_tree must be a string.
This error is thrown even if the column is not changed at all, e.g. it cannot validate the valid existing data.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14 and above
| PHP version      | 7.1 
| Operating system | debian 8

**Comment by schmunk42** [comment]
Which database (MySQL, Maria, Percona) and version are you using? There are differences in the implementation.

**Comment by yavuzg2** [comment]
5.7.21 MySQL Community Server (GPL)

**Comment by schmunk42** [comment]
Is the column required (NOT NULL)?

**Comment by yavuzg2** [comment]
The column is nullable and the default is null

**Comment by schmunk42** [comment]
While a JSON validator would be nice, I think the column is more or less a string internally.
Yii can't know about the fact you manually remove the column from the form.

**Comment by SilverFire** [comment]
@yavuzg2 Could you check with the fix I've applied?
