### ISSUE TITLE
Change findModel() error message

### ISSUE THREAD

**Issue by mtangoo** [yiisoft/yii2-gii#353]
### What steps will reproduce the problem?
Error Message produced by default by Gii findModel() in the CRUD controller is confusing. One of our developers used ample time to find why the action was not accessible because the message on the browser (404 - Requested page does not exist) and he thought page mean what it is usually associated with in common internet language.

I suggest error to explicitly state the model that does not exist to make sure that there is no confusion. Message am suggesting is something like

~~`404 - Requsted Resource  {Singular Model Name} does not exist` or~~ something that explictly state that it is resource rather than page which was not found!

### What's expected?
N/A

### What do you get instead?
N/A

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14
| PHP version      | N/A
| Database version | N/A
| Operating system | N/A

**Comment by mtangoo** [comment]
What do you mean by that?

**Comment by samdark** [comment]
He means that error message exposes structure of your application and that it could be used by a hacker to understand where to point his attacks.

**Comment by mtangoo** [comment]
> He means that error message exposes structure of your application and that it could be used by a hacker to understand where to point his attacks.

Aha! I get his point. But my poor suggestion was just a way to show that we need a better message. The current is misleading. I withdraw my message suggestion but I hope you understand my main concern!

**Comment by mtangoo** [comment]
>"Requested resource" doesn't mean anything to non-developer so I don't think it makes sense to show such message.

That's right. I'm not even proposing that should be the message. My point is the current message is misleading to developers and can cause headache especially to Junior developers. Am not the right person to propose alternative message as well proven above. But my point stands still!

**Comment by rob006** [comment]
There is an error message in debug toolbar, with full stack trace of error - this should make quite obvious what is the source of error.

**Comment by mtangoo** [comment]
@rob006 I had first hand experience with a Junior developer who interpreted page not found as a problem in the routing than a missing data. My experience (and of many seniors) will make it a breeze to find such trivial error. I was speaking for newbies to Yii.

Since this seems to be almost lone case, I will close it.
