### ISSUE TITLE
Tinyint column validation error `column must be a string`

### ISSUE THREAD

**Issue by vijayarun** [yiisoft/yii2-gii#355]
### Got validation error

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 5.6
| Database version | Mysql 5.7
| Operating system | Ubuntu 16.04 LTS

**Comment by rob006** [comment]
Duplicate of #340

**Comment by rob006** [comment]
@samdark @cebe Maybe we should finally release 2.0.7 (or at least 2.0.6.1)? This issue was fixed 2 months ago and 2.0.7 milestone is not even close to release. This issue will keep popping up until next release with this fix.
