### ISSUE TITLE
Replace deprecated ::className() with ::class

### ISSUE THREAD

**Issue by Deele** [yiisoft/yii2-gii#356]
Since 2.0.14. On PHP >=5.5, use `::class` instead of `::className()`.

See https://github.com/yiisoft/yii2/blob/master/framework/base/BaseObject.php#L82

At least 11 results https://github.com/yiisoft/yii2-gii/search?q=::className()

**Comment by samdark** [comment]
Yes, in the next major version that is for Yii 2.1 we can do that.

**Comment by desenvolvedorindie** [comment]
Probabily need check version of php like this

version_compare(phpversion(),'5.5.0')

To keep compatibility

**Comment by samdark** [comment]
No. The change should be done in https://github.com/yiisoft/yii-gii instead.

**Comment by sokollondon** [comment]
More than a year has passed. Problem still exists. PHPStorm inspection shows warning!
Help )

**Comment by schmunk42** [comment]
@sokollondon Yii2 is compatible with PHP 5.4 but `:class` is only available from 5.5 - so this won't happen it Yii2.

**Comment by machour** [comment]
Since Yii2 is still going to be used for a long time, I'm wondering if it's worth providing an option to generate PHP7 code.. 🤔

**Comment by schmunk42** [comment]
> Since Yii2 is still going to be used for a long time, I'm wondering if it's worth providing an option to generate PHP7 code..

Yeah, it's a valid point. Is there more than just `:class`? This could be done with an option.

**Comment by Deele** [comment]
> 
> 
> > Since Yii2 is still going to be used for a long time, I'm wondering if it's worth providing an option to generate PHP7 code..
> 
> Yeah, it's a valid point. Is there more than just `:class`? This could be done with an option.

That could be done with just another template bundled together with core Gii, I approve.

**Comment by rob006** [comment]
I'm not sure if we need this as an option. We could just release new major release (2.2) which will generate code according to current standards (everything before PHP 7.1 is already EOLed) and everyone who stuck in PHP 5 age could use old releases of Gii (2.0 or 2.1).

**Comment by albertvangink** [comment]
Can i Find "className()" & Replace them all with "class" safe at a fresh install?

**Comment by samdark** [comment]
Likely yes.

**Comment by albertvangink** [comment]
There were a few files that didn't like it :-(

C:\xampp\htdocs\basic\vendor\sebastian\type\src\ObjectType.php

C:\xampp\htdocs\basic\vendor\yiisoft\yii2-gii\src\generators\model\Generator.php

C:\xampp\htdocs\basic\vendor\yiisoft\yii2\base\BaseObject.php --> Parse error: syntax error, unexpected '{', expecting '(' in C:\xampp\htdocs\basic\vendor\yiisoft\yii2\base\BaseObject.php on line 85

**Comment by rob006** [comment]
You should find `::className()` and replace by `::class`. But this is not completely safe, since some classes may use `className()` method for different purposes, so it depends on your codebase. There are also cases where it won't work even for Yii-like code (for example `$model::className()` vs `$model::class` - former variant is supported since PHP 8.0, so it may not work on older versions of PHP), so you need to review these changes.

But above all: you should not modify files in `vendor` directory.

**Comment by albertvangink** [comment]
No, a mass action with find and replace all seems not wise. Thank you
