### ISSUE TITLE
why not make property ($resource_id) as model class property?

### ISSUE THREAD

**Issue by brookin** [yiisoft/yii2-gii#357]
### What steps will reproduce the problem?
```
/*
 * @property int $resource_id
 * @property int $task_id
 * @property string $author_id
 */
```

when gii generate model, why not make property ($resource_id) as model class(object) property?

query database table schema when use model, although db component can use `enableSchemaCache`. but it's expensive.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | yii2 
| PHP version      | php-5.6
| Database version | mysql-5.6
| Operating system | centos7

**Comment by samdark** [comment]
Because it's how Yii ActiveRecord works. It's not a mapper.
