### ISSUE TITLE
Wong Rule in Gii Model Generator for TinyInt type Fields

### ISSUE THREAD

**Issue by buttflattery** [yiisoft/yii2-gii#358]
### What steps will reproduce the problem?

- Create a field in the table with a name say  `delivered` `TINYINT() NOT NULL DEFAULT 0` 
- Generate the Model from Gii 

### What's expected?
the rule added for the above field should be 

`[['delivered'], 'integer', 'max' => 1],`

### What do you get instead?
`
[['delivered'], 'string', 'max' => 1],`

Which does not allows saving the record if I pass `0`, `1` or boolean to the field it throws the following error for the validation on calling `$model->save()`

> Delivered must be a string.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |2.0.15
| PHP version      | 5.6
| Database version | 5.6.33-0ubuntu0.14.04.1
| Operating system | Ubuntu 14.04.1

**Comment by samdark** [comment]
Solved in master. Will release soon.
