### ISSUE TITLE
[feature] Option to create new applications

### ISSUE THREAD

**Issue by slinstj** [yiisoft/yii2-gii#359]
Based on [this Yii2 Guide](https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/topic-adding-more-apps.md), maybe Gii could manage new apps creation (like blog, api, etc) instead users have to do it manually (multiple file edits, search/replace strings, very error prone).  

I know it is not a frequent need but I think Modules are even less (based in my 8/9 years of experience using Yii) but they are there.

I think it is something to think about.

**Comment by samdark** [comment]
You mean advanced template? It will not be there in 2.1 so won't implement it.

**Comment by schmunk42** [comment]
> I know it is not a frequent need but I think Modules are even less

Applications are also modules, we're using the module generator several times a week.

**Comment by slinstj** [comment]
Ok, I have to follow 2.1 closer. Thank you.
