### ISSUE TITLE
gii model generator not working after updating 2.0.3 to 2.0.4

### ISSUE THREAD

**Issue by benmadin** [yiisoft/yii2-gii#36]
Hi,

We updated composer last night for some other dependancies, and appear to have upgraded gii from 2.0.3 to 2.0.4, and the gii model builder doesn't ... do anything when clicking on preview.

The crud generator appears to work with 2.0.4

When we fixed gii at 2.0.3, and ran another composer update, it downgraded and the model generator works fine with 2.0.3.

cheers

Ben

FWIW

composer.lock @ 2.0.4

          "name": "yiisoft/yii2-gii",
            "version": "2.0.4",
            "source": {
                "type": "git",
                "url": "https://github.com/yiisoft/yii2-gii.git",
                "reference": "e5a023e8779bd774194842ec1b8fb4917cf04007"
            },

and 2.0.3

           "name": "yiisoft/yii2-gii",
            "version": "2.0.3",
            "source": {
                "type": "git",
                "url": "https://github.com/yiisoft/yii2-gii.git",
                "reference": "bb79aeafa8e3b89dd25e07ac895b269680e537a8"
            },

**Comment by samdark** [comment]
Could you provide DB schema and data you're entering into form?

**Comment by ruffiem** [comment]
Hey.

I had the same issue and I fixed it just now. Open the file /vendor/yiisoft/yii2-gii/views/default/view/view.php and watch for the lines 45 and 48 where the buttons are created and append a value attribute with arbitrary content (I chose 'value' => 'true').

Works like a charm.

![ss](https://cloud.githubusercontent.com/assets/1785492/7706363/52ffc284-fe4a-11e4-884e-a0d759d2166a.png)

**Comment by benmadin** [comment]
Ok great, thanks for sharing this, I hadn't yet made it to putting up a test case, but I'll try this and see if it resolves it,

Cheers

Ben

**Comment by ruffiem** [comment]
This is a temporary hack @benmadin as the vendor folder will update and get rid of changes on the next composer update but it's useful for an urgent usage.

**Comment by samdark** [comment]
So what about DB schema to reproduce the issue?

**Comment by ruffiem** [comment]
Hi Sam, here's mine [link to mrvyii.sql](http://we.tl/4nibBeRmUJ)

**Comment by samdark** [comment]
Thanks!

**Comment by samdark** [comment]
Tried current code with Chrome, FF, Opera, IE, Edge. Works flawlessly.
