### ISSUE TITLE
yii gii/crud update view

### ISSUE THREAD

**Issue by tsanchev** [yiisoft/yii2-gii#363]
### What steps will reproduce the problem?

`yii gii/crud --controllerClass=backend\modules\employeeBankPayment\controllers\DefaultController --modelClass=backend\modules\employeeBankPayment\models\EmployeeBankPayment --viewPath=@backend\modules\employeeBankPayment\views\default  --searchModelClass=backend\modules\employeeBankPayment\models\EmployeeBankPaymentSearch  --overwrite=1 --enableI18N=1 --interactive=0`

### What's expected?

    $this->title = Yii::t('app', 'Update Employee Bank Payment: {nameAttribute}', [
        'nameAttribute' => $model->employee_bank_payment_id,
    ]);

### What do you get instead?

    $this->title = Yii::t('app', 'Update Employee Bank Payment: ' . $model->employee_bank_payment_id, [
        'nameAttribute' => '' . $model->employee_bank_payment_id,
    ]);

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.16-dev
| PHP version      | PHP 5.6.9

**Comment by vanilevsky** [comment]
Fixed?

**Comment by samdark** [comment]
Yes. Thanks.
