### ISSUE TITLE
Wrong capitals for class/files when table is uppercase

### ISSUE THREAD

**Issue by slinstj** [yiisoft/yii2-gii#366]
### What steps will reproduce the problem?
yiisoft/yii2-gii uses `BaseInflector::id2camel()` to generate class names but, when getting upper case table names from db like `MY_TABLE`, id2camel() does not work properly.

If it is ok, I could do a PR removing id2camel() and doing an inline conversion inside `Generator::generateClassNames()`.

### What is the expected result?
```
'MY_TABLE' --> MyTable
```

### What do you get instead?
```
'MY_TABLE' --> MYTABLE
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      |  7.1.17
| Operating system | Win10

**Comment by slinstj** [comment]
Related: https://github.com/yiisoft/yii2/issues/16316

**Comment by samdark** [comment]
How would it work with `MyTable`?

**Comment by slinstj** [comment]
Note sure what you mean but I would just change the generated class and file names. The table set in getTableName would not change. I have this working for MSSQL and MySQL (I extended the Generator).

On the other hand, I must to say that I am not familiar with Postgre.

**Comment by slinstj** [comment]
AFAICS, it would not change. The change would affect only `MY_TABLE` since we have all uppercase and **underscores** separeting the words. `MyTable` would not be affected.

**Comment by samdark** [comment]
How would you implement that?

**Comment by slinstj** [comment]
```php
// I changed this in generateClassnames()
return $this->classNames[$fullTableName] = Inflector::id2camel($schemaName.$className, '_');

// For this (not beauty but works for my companie DBs [mysql, mssql])
return $this->classNames[$fullTableName] = strtr(ucwords(implode(' ', explode('_', strtolower($schemaName.$className)))), [' ' => '']);

// To implement it for MyTable I just would user Inflector::camel2words()
// (preferably in a bit more clean way than this)
return $this->classNames[$fullTableName] = strtr(ucwords(implode(' ', explode('_', strtolower(strtr(Inflector::camel2words($schemaName.$className), [' ' => '_']))))), [' ' => '']);

```

**Comment by samdark** [comment]
It won't work: https://3v4l.org/164si

**Comment by slinstj** [comment]
May be your test function `yiiCamelize()` is wrong.
Correct should be like `Inflector::camel2words()`:

```php
public static function camel2words($name, $ucwords = true)
    {
        $label = strtolower(trim(str_replace([
            '-',
            '_',
            '.',
        ], ' ', preg_replace('/(?<![A-Z])[A-Z]/', ' \0', $name))));

        return $ucwords ? ucwords($label) : $label;
    }
```

**Comment by slinstj** [comment]
Just tested here breaking it in parts:

```php
$data = [
            'MY_TABLE' => 'MyTable',
            'MyTable' => 'MyTable',
            'my_table' => 'MyTable',
            'myTable' => 'MyTable',
        ];

        // strtr(ucwords(implode(' ', explode('_', strtolower(strtr(Inflector::camel2words($schemaName.$className), [' ' => '_']))))), [' ' => '']);
        function genNames($input) {
            $cc = Inflector::camel2words($input);
            $cca = strtr($cc, [' '=>'_']);
            $ccal = strtolower($cca);
            $ccala = explode('_', $ccal);
            $ccalai = implode(' ', $ccala);
            $ccalaiw = ucwords($ccalai);
            $final = strtr($ccalaiw, [' '=>'']);
            return $final;
        }

        $result = '';
        foreach ($data as $orig => $expected) {
            $finalName = genNames($orig);
            $result .= $orig . ' would be changed to ' . $finalName . '<hr>';
        }

        return $result;
```
Result:

    MY_TABLE would be changed to MyTable
    MyTable would be changed to MyTable
    my_table would be changed to MyTable
    myTable would be changed to MyTable

**Comment by samdark** [comment]
OK. That looks like it.

**Comment by slinstj** [comment]
Yeah, I am on it. I would already do but i had no time this weekend. I'll do this week.  :thumbsup:

**Comment by slinstj** [comment]
@samdark, should I create some tables with variated names (underlines, hyphens, uppers, etc) inside `tests/data/sqlite.sql` just to be able to create a test in `tests/generators/ModelGeneratorTests.php` or would you have a better approach?

**Comment by slinstj** [comment]
I think I found a better approach: it would be to mock `ModelGenerator` overriding `getTableNames()` since I want to test only name conversions.

**Comment by samdark** [comment]
Yep, mock is better.

**Comment by slinstj** [comment]
I did just basic tests for that specific method. So I just turned that method public to test against it. I know it is not the preffered way for tests but I hope it to be enough. If not, let me know.

**Comment by jkovacsab** [comment]
This last update broke my application's ability to update the existing model files with old case, and instead it creates new models of a new filename and new classname.  How do I configure Gii to revert to the previous functionality and preserve the DB table names as classnames and filenames?

My DB table name is ABBRMyTable on purpose. My expected Model class name and filename is ABBRMyTable, i.e. no change, but I get AbbrmyTable.

Another example is MyTableABBR, and I expected no change in the case, but I am getting MyTableAbbr.

Let me know how to resolve soon, so I can continue using Gii for model regeneration.

**Comment by slinstj** [comment]
Models' names should be PSR compliant. That is why this change was done. 

For your specific case (and may others), it could be implemented a new attribute to `form` like `dont touch table name`. But I am not sure that @samdark would agree with that. For now, you could just preview the generated model and copy/paste the lines in your current code. 

BTW, keep in mind that Gii should be used primarily to "bootstrap" your models' code.

**Comment by samdark** [comment]
Yes, that could be a problem. Technically it's a breaking change so either next version should be major or we should make it configurable and not turned on by default.

**Comment by jkovacsab** [comment]
Thanks for considering making this a configurable option in Gii to allow for no change in the case.

Regarding the typical usage of Gii for bootstrapping models, our organization has a non-typical usage, borrowed from other language ORMs. We extended the Gii Model Generator to separate models and base models. The base model is continuously generated for modified columns and relationships after DB migrations, and the application logic lives in the models that are not regenerated. In this usage, I cannot easily copy the preview to a different file name but prefer to override the existing base model file.

**Comment by samdark** [comment]
It should not be exact name, just the same way it was before and yes, it should be default. You could work on it.

**Comment by slinstj** [comment]
PR done. Not sure if the name `Force PSR Class Names` is "cool" but seems good to me. However, suggestions for change it are welcome.

PS: the feature is now optional and the checkbox is not even displayed in the form except when table name contains *.
