### ISSUE TITLE
Creating CRUD into a module, Gii will preview 2 files as they will be outside the module

### ISSUE THREAD

**Issue by realtebo** [yiisoft/yii2-gii#37]
[Please, fix the title, my english is so bad]

I'm using the advanced template as base for my app.
I've succesfully generated (using gii) the module 'admin'
I'm using the Gii CRUD generator from v 2.0.4 to create the full crud for `User` class (part of the advanced template, unmodified until now).

These are entered params:
- Model Class: `common\models\User`
- Search Model Class: `frontend\modules\admin\models\UserSearch`
- Controller Class: `frontend\modules\admin\controllers\UserController`
- View Path: `frontend\modules\admin\views\user`

Look at list of generated file: the first two are outside the module. 

```
modules\admin\controllers\UserController.php
modules\admin\models\UserSearch.php
frontend\modules\admin\views\user\_form.php
frontend\modules\admin\views\user\_search.php
frontend\modules\admin\views\user\create.php
frontend\modules\admin\views\user\index.php
frontend\modules\admin\views\user\update.php
frontend\modules\admin\views\user\view.php
```

This is **only a visual bug** because Gii will create all the files in the right folder:

```
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        new file:   frontend/modules/admin/controllers/UserController.php
        new file:   frontend/modules/admin/models/UserSearch.php
        new file:   frontend/modules/admin/views/user/_form.php
        new file:   frontend/modules/admin/views/user/_search.php
        new file:   frontend/modules/admin/views/user/create.php
        new file:   frontend/modules/admin/views/user/index.php
        new file:   frontend/modules/admin/views/user/update.php
        new file:   frontend/modules/admin/views/user/view.php
```

**Comment by realtebo** [comment]
UPDATED: files will be generated rightly in the frontend folders.
so this is only a visual bug in the preview list

**Comment by cebe** [comment]
> This is only a visual bug

is it possible to provide a screenshot of the issue?

**Comment by realtebo** [comment]
"It's only a visual bug", I mean that the infos that Gii is showing are not all right, but at the end Gi is doing the work of creating file well.

Until Monday I'll not be able to make a new screenshot, but, really, I've copied the list of generated file copying/pasting from gii page. Why do you need a screenshot? I copied all of the infos

**Comment by cebe** [comment]
sorry, I misunderstood the "visual bug". Have it reproduced now.

**Comment by cebe** [comment]
The issue is caused because your view path is not correct, it is a relative path that works just because PHPs working directory seems to be the root of the application. you should either use an absolute path or use an alias: `@frontend/modules/admin/views/user`

**Comment by realtebo** [comment]
Invalid path alias: @frontend\modules\admin\views\user

**Comment by lynicidn** [comment]
@cebe write
`@frontend/modules/admin/views/user`
@realtebo  write
`@frontend\modules\admin\views\user`

**Comment by realtebo** [comment]
@lynicidn : just tried, same Exception

**Comment by lynicidn** [comment]
should work - show screen or full stack

**Comment by realtebo** [comment]
Ok, using slash instead of backslash works. 

Thanks @cebe and @lynicidn

**Comment by realtebo** [comment]
Also, I suggest  anyway that preview of file name list should use the full path to avoid confusion.

Now all is working, but the list show nothing about the `frontend` folder, so user, like me, can think that files will not be created under the `frontend` folder.

![cattura](https://cloud.githubusercontent.com/assets/1268699/7676116/d5d9c728-fd40-11e4-96e5-0138301f98c4.JPG)

**Comment by lynicidn** [comment]
it mean that gii run in current `*end`

**Comment by realtebo** [comment]
Absolutely no, I'm using it as 
    localhost/gii

**Comment by realtebo** [comment]
Yes, I understand now. 

It could be, because I've moved my frontend to the root. I understand clearly now. It's a non-standard installation, so Gii will not show info as in normally.

Thanks for your patience.

**Comment by lynicidn** [comment]
see here - https://github.com/yiisoft/yii2-gii/blob/master/Generator.php#L277 - `relativePath`

**Comment by lynicidn** [comment]
and this method - https://github.com/yiisoft/yii2-gii/blob/master/CodeFile.php#L110

**Comment by realtebo** [comment]
Yes, I understood. 

I think, anyway, it should show FULL paths.

**Comment by lynicidn** [comment]
do it problem with longer path - /this/is/my/super/puper/path/to/web/sites/frontend/public vs public

**Comment by LAV45** [comment]
Maybe frontend/public
Still may be backend/public

**Comment by cebe** [comment]
@lynicidn gii will show this relative to the application path.

**Comment by ArvindU** [comment]
thank you @cebe  your suggestion was really helpful for me
