### ISSUE TITLE
default empty string is error

### ISSUE THREAD

**Issue by y284663247** [yiisoft/yii2-gii#373]
### What steps will reproduce the problem?
```
'title' => $this->string()->notNull()->defaultValue('')->comment('主题名称'),
```
default empty string is error，the value in mysql chang `'\'\''`,but default is must to params

### What's expected?
can default empty string 

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.1.18 
| Database version | mysql 5.6
| Operating system | Darwin / 17.6.0

**Comment by y284663247** [comment]
the code as follow
```
$this->createTable('{{%subject_item}}', [
    'id' => $this->primaryKey()->unsigned(),
    'subject_id' => $this->integer()->unsigned()->notNull()->defaultValue(0)->comment('类型ID'),
    'title' => $this->string(50)->notNull()->defaultValue('')->comment('功能名称'),
    'url' => $this->string(100)->notNull()->defaultValue('')->comment('功能链接'),
    'intro' => $this->string(100)->notNull()->defaultValue('')->comment('功能说明'),

    'status' => $this->tinyInteger()->unsigned()->notNull()->defaultValue(10)->comment('功能状态'),
    'created_at' => $this->integer()->unsigned()->notNull()->defaultValue(0)->comment('创建时间'),
    'updated_at' => $this->integer()->unsigned()->notNull()->defaultValue(0)->comment('更新时间'),
 ], $tableOptions);
```
the database columns as follow:

<img width="825" alt="wx20180622-141809 2x" src="https://user-images.githubusercontent.com/7445875/41760664-1e92beea-7627-11e8-82df-34706fb35b47.png">


I want to know how to setting the varchar columns to empty string as default, thank!

**Comment by y284663247** [comment]
i am sorry,i find mysql5.7 is right but mariadb 10 is not right,think!

**Comment by samdark** [comment]
@SamMousa you should be interested in it...

**Comment by SamMousa** [comment]
Thanks. Or should core team be more interested :D  @y284663247 I'll release a mariadb extension soon to fix mariadb issues!

**Comment by samdark** [comment]
Closing it here then.
