### ISSUE TITLE
new Typeahead version bump

### ISSUE THREAD

**Issue by razvanphp** [yiisoft/yii2-gii#38]
Hello,

Since there is a new Typeahead version 0.11 released, and some other libraries use it already, there is an incompatibility when yii-gii is included.
https://github.com/twitter/typeahead.js/releases/tag/v0.11.1

````
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for 2amigos/yii2-type-ahead-widget ~1.1 -> satisfiable by 2amigos/yii2-type-ahead-widget[1.1].
    - yiisoft/yii2-gii 2.0.4 requires bower-asset/typeahead.js 0.10.* -> satisfiable by bower-asset/typeahead.js[v0.10.5].
    - Conclusion: remove bower-asset/typeahead.js v0.10.5
    - Installation request for yiisoft/yii2-gii * -> satisfiable by yiisoft/yii2-gii[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4].
````

Can you already use the new version? some event names changed, but very useful others like `changed` were added.

Thank you!

**Comment by samdark** [comment]
Yes, it could be updated. Do you want to handle it by providing a pull request?
