### ISSUE TITLE
Ambiguous usage of pjax

### ISSUE THREAD

**Issue by bscheshirwork** [yiisoft/yii2-gii#386]
### What steps will reproduce the problem?
Use crud generator

### What's expected?
pjax template exclude "create" button
```php
    <p>
        <?= "<?= " ?>Html::a(<?= $generator->generateString('Create ' . Inflector::camel2words(StringHelper::basename($generator->modelClass))) ?>, ['create'], ['class' => 'btn btn-success']) ?>
    </p>

<?= $generator->enablePjax ? "    <?php Pjax::begin(); ?>\n" : '' ?>
<?php if(!empty($generator->searchModelClass)): ?>
<?= "    <?php " . ($generator->indexWidgetType === 'grid' ? "// " : "") ?>echo $this->render('_search', ['model' => $searchModel]); ?>
<?php endif; ?>
```

### What do you get instead?
pjax template included "create" button
```php
<?= $generator->enablePjax ? "    <?php Pjax::begin(); ?>\n" : '' ?>
<?php if(!empty($generator->searchModelClass)): ?>
<?= "    <?php " . ($generator->indexWidgetType === 'grid' ? "// " : "") ?>echo $this->render('_search', ['model' => $searchModel]); ?>
<?php endif; ?>


    <p>
        <?= "<?= " ?>Html::a(<?= $generator->generateString('Create ' . Inflector::camel2words(StringHelper::basename($generator->modelClass))) ?>, ['create'], ['class' => 'btn btn-success']) ?>
    </p>
```

https://github.com/yiisoft/yii2-gii/blob/6d30fa9571379ffff98a31597dc5bbf26bb83248/src/generators/crud/default/views/index.php#L34-L36

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |dev
| PHP version      |7.2.11
| Database version |
| Operating system |

**Comment by bscheshirwork** [comment]
This action is not a pjax action and can be place outside pjax container for avoid unnecessery redirect after pjax fail

**Comment by samdark** [comment]
OK. Could you send a pull request fixing it?

**Comment by SOHELAHMED7** [comment]
Either we can go with @bscheshirwork  or we can add a attribute `data-pjax="0"` [link](https://www.yiiframework.com/doc/api/2.0/yii-widgets-pjax)

**Comment by samdark** [comment]
Yes. Correct.

**Comment by SOHELAHMED7** [comment]
Should I go ahead with PR?

**Comment by bscheshirwork** [comment]
@SOHELAHMED7 @samdark 
```
data-pjax="0"
```
is not a correct way for new project, 
but this variant is safe for existing projects; 
we can use css for nested rules.

**Comment by samdark** [comment]
@bscheshirwork agree.
