### ISSUE TITLE
Error in debug console for non-loaded message category

### ISSUE THREAD

**Issue by bscheshirwork** [yiisoft/yii2-gii#393]
### What steps will reproduce the problem?
/gii/crud for module with your own i18n (dynamic load in init, non-bootstrap)

### What's expected?
all is ok

### What do you get instead?
```
10:47:14.283 | error | yii\i18n\PhpMessageSource::loadFallbackMessages | The message file for category 'reason' does not exist: /var/www/html/common/messages/ru-Ru/reason.php Fallback file does not exist as well: /var/www/html/common/messages/ru/reason.php
-- | -- | -- | --



```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |dev
| PHP version      |7.2.12
| Database version |
| Operating system |

**Comment by samdark** [comment]
What do you mean by "all is OK"? What should framework do if there's no translation and it's told to translate?

**Comment by bscheshirwork** [comment]
Not "it's told to translate". 

Inject template with conrete string in first parametr of Yii::t

**Comment by bscheshirwork** [comment]
I think this happens becouse model have unresolved translation for gii
