### ISSUE TITLE
[Gii] Crud Generator table name 'd_xxxx' is wrong

### ISSUE THREAD

**Issue by atmanegara** [yiisoft/yii2-gii#397]
### What steps will reproduce the problem?
table name is d_polri
using Gii 
1. model generator
2. CRUD Generator
it's OK, but result for name folder view is 'dpolri' not 'd-polri' 
![image](https://user-images.githubusercontent.com/9096711/52514232-e86a6680-2c4a-11e9-97a1-ef3a3495b2b1.png)
so when it's accessed url is not found
![image](https://user-images.githubusercontent.com/9096711/52514264-1b145f00-2c4b-11e9-9f70-bd79e7433a40.png)

### What is the expected result?
page index
### What do you get instead?
rename folder view dpolri to d-polri
![image](https://user-images.githubusercontent.com/9096711/52514348-cfae8080-2c4b-11e9-8e4a-9f4236267770.png)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.16
| PHP version      | 7.1.20
| Operating system | Windows 10

**Comment by schmunk42** [comment]
Related commit: https://github.com/yiisoft/yii2/commit/7c04ff048f83e640c907312d39ce67a4bbc13594#diff-cc9bfd727870423bb306f65b04c230d4R102

I added a strict param to `camel2id` which AFAIR is not used by gii.

**Comment by machour** [comment]
Just confirmed it. Passing strict as `true` fixes it, thank you @schmunk42!
Opening a PR.

**Comment by schmunk42** [comment]
@machour Please think about making this an optional param for the generator as it might break existing CRUDs if they are regenerated. There are use-cases where you want the current behavior.

**Comment by machour** [comment]
Oh, I thought that [yiisoft/yii2@7c04ff0](https://github.com/yiisoft/yii2/commit/7c04ff048f83e640c907312d39ce67a4bbc13594#diff-cc9bfd727870423bb306f65b04c230d4R102) broke BC and I was restoring it in #398, I didn't see that it was from 2014 :)

Would you expose this new parameter in cli & ui, or just allow to configure it through DI?

**Comment by schmunk42** [comment]
To me DI would be enough to cover this edge-case

**Comment by samdark** [comment]
We're going to release 2.1 version so some minor BC breaks should be OK.
