### ISSUE TITLE
change model generator to use class instead of className()

### ISSUE THREAD

**Issue by Isitar** [yiisoft/yii2-gii#400]
Hello

I would appreciate if gii uses ::class instead of className() in templates. 
Is there any reason this isn't done? className() is depricated and slower than ::class.

Example-Line to be changed in model generator for relations
https://github.com/yiisoft/yii2-gii/blob/bfe6044f7ee8089923c0bbfda7394a94925c4b0e/src/generators/model/Generator.php#L533

**Comment by alexkart** [comment]
Hello, maybe it's done for compatibility with PHP 5.4?

**Comment by machour** [comment]
`::class` was implemented in PHP 5.5 but Yii2 tries to be compatible with PHP 5.4, so I don't think we will change that. @samdark ?

**Comment by machour** [comment]
We could consider dropping PHP 5.X for 2.1, as we did for swiftmailer

**Comment by samdark** [comment]
I don't think it worth doing in 2.x. For 3.x — definitely.
