### ISSUE TITLE
Issue by using yii/gii and Ingres II DB

### ISSUE THREAD

**Issue by goldenone** [yiisoft/yii2-gii#408]
### What steps will reproduce the problem?
Using yii with an Ingres II database
### What's expected?
I would like to create with gii some models and classes like 'search', 'controller', .
### What do you get instead?
yii\base\NotSupportedException: Connection does not support reading schema information for '{ingres ii}' DBMS. in /var/www/html/abntstats/vendor/yiisoft/yii2/db/Connection.php:827

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | dev - 2.0.16
| PHP version      | PHP V. 7
| Database version | Ingres II 
| Operating system | Apache/2.4.18 (Ubuntu)
[StackTrace.txt](https://github.com/yiisoft/yii2-gii/files/3079816/StackTrace.txt)

[connection-file.txt](https://github.com/yiisoft/yii2-gii/files/3079852/connection-file.txt)

**Comment by machour** [comment]
The problem seems that Gii/DB component doesn't know how to inspect tables to retrieve fields when the driver is Ingres.

Never used Ingres, so I don't know if it's technically impossible, or just not implemented yet.

**Comment by samdark** [comment]
Which DB driver is used? Yii isn't supporting Ingres out of the box.

**Comment by goldenone** [comment]
Thanks for your fast reply! The Ingres ODBC driver in version 3.5 is used.

**Comment by samdark** [comment]
I'm asking about PHP driver i.e. which package is used to connect to it.

**Comment by goldenone** [comment]
I have used php -v and got:

PHP 7.0.32-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.32-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans

**Comment by samdark** [comment]
Can you post your `composer.json`?

**Comment by goldenone** [comment]
Sure :) 
[composer.txt](https://github.com/yiisoft/yii2-gii/files/3080729/composer.txt)

**Comment by samdark** [comment]
How is your database connection configured?

**Comment by goldenone** [comment]
Do you mean something like the connection file? If yes, you can find this at the beginning of this post.

**Comment by samdark** [comment]
OK. Seems that @machour is correct. Ingres seems to be different from databases we're supporting out of the box so the only way to make it fully work including schema inspection is wring a custom driver for it like  https://github.com/yiisoft/yii2/tree/master/framework/db (cubrid, mssql, mysql, oci etc.)

We do not have plans adding support for it and quick search doesn't reveal anything ready so that leaves you with implementing it yourself. If you'll decide doing it, consider releasing it as an extension.

**Comment by goldenone** [comment]
@samdark: macchour had the idea that I could create the classes at a testsystem and use the files at my productive system. Could this work?

**Comment by samdark** [comment]
Try it. I have no experience with Ingres II so can not really answer that.

**Comment by goldenone** [comment]
I have tried it but no chance. I got the same error like if I want to create some files with gii: Connection does not support reading schema information for '{ingres ii}' DBMS.
