### ISSUE TITLE
New or removed lines are not highlighted

### ISSUE THREAD

**Issue by albertborsos** [yiisoft/yii2-gii#410]
### What steps will reproduce the problem?

Update a file with additional or removed lines. (Modified lines are OK)

### What's expected?

New lines highlighted in green, removed lines highlighted in red.

### What do you get instead?

They are not highlighted.

### Additional info

![Képernyőfotó 2019-08-12 - 10 37 02](https://user-images.githubusercontent.com/7307145/62853809-c0d58300-bced-11e9-9967-84e9b1f81cfd.png)

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.24
| Gii version |  2.1.0
| PHP version      | 7.3.6
| Database version |
| Operating system |

**Comment by samdark** [comment]
![image](https://user-images.githubusercontent.com/47294/62854480-20389080-bcf8-11e9-8036-c43bc3f09d08.png)

**Comment by samdark** [comment]
![image](https://user-images.githubusercontent.com/47294/62854589-6beb3a00-bcf8-11e9-935e-aa730e572e3a.png)

**Comment by samdark** [comment]
Is there anything special about your case?

**Comment by albertborsos** [comment]
`.ChangeInsert .Right` css rule is missing from my css rules.

![Képernyőfotó 2019-08-12 - 11 02 33](https://user-images.githubusercontent.com/7307145/62854824-c7b1c500-bcf0-11e9-9793-1bbdb1e67d95.png)
![Képernyőfotó 2019-08-12 - 11 02 17](https://user-images.githubusercontent.com/7307145/62854825-c7b1c500-bcf0-11e9-8610-549528fbe1d8.png)

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2-gii/blob/master/src/assets/scss/main.scss#L310

**Comment by samdark** [comment]
Not sure why it's missing for you but it's there.

**Comment by albertborsos** [comment]
Yes, it is there for `.DifferencesSideBySide `, but not for `. DifferencesInline`. I will make PR, since I found it. I thought it will be more complicated.

**Comment by albertborsos** [comment]
Which command compiles the scss files to css?

**Comment by samdark** [comment]
https://sass-lang.com/
