### ISSUE TITLE
Comments which includes @var properties aren't DocBlocks

### ISSUE THREAD

**Issue by ricpelo** [yiisoft/yii2-gii#425]
The comments which include `@var` properties aren't DocBlocks. They must be started with `/**`, not `/*`.

The issue affects both the yii2-gii code and the code generated by gii.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.32
| Yii2-gii version | 2.1.4
| PHP version      | 7.3
| Database version |
| Operating system | Linux

**Comment by samdark** [comment]
They're called vardoc and originated from Eclipse PDT. Then they were adopted by all other IDEs. They're well supported. What is the issue with these?

**Comment by ricpelo** [comment]
> They're called vardoc and originated from Eclipse PDT. Then they were adopted by all other IDEs. They're well supported. What is the issue with these?

I didn't knew that. I only tried Visual Studio Code with PHP Intelephense extension as well as Atom with PHP Serenata package and they don't like `@var` outside DocBlocks.

**Comment by samdark** [comment]
I see. If there are editors that can't work with such format, let's fix it.

**Comment by ricpelo** [comment]
Oops, I just tested it and I think I made a mistake. Visual Studio Code with PHP Intelephense extension _does_ honor `/* @var */` syntax and _doesn't_ honor `/** @var */` syntax. On the other hand, Atom doesn't honor neither. Could you please roll back the PR until we can make sure it worth merging it? After some tests, it seems to brings more harm than benefit. Thanks and sorry!

**Comment by samdark** [comment]
:)

**Comment by samdark** [comment]
Reverted.

**Comment by ricpelo** [comment]
Thanks again! I'll investigate further.

**Comment by rob006** [comment]
Vardoc and phpdoc have different order:

```
/* @var $variableName type */
/** @var type $variableName */
```

So simple removing or adding `*` is not enough. 

It is also questionable if using dockblocs is correct in some cases (like in views, where there is no structural element  to document), and some tools complains about it (PHP-CS-Fixer have have fixers for this).

**Comment by ricpelo** [comment]
> Vardoc and phpdoc have different order:
> 
> ```
> /* @var $variableName type */
> /** @var type $variableName */
> ```
> 
> So simple removing or adding `*` is not enough.
> 
> It is also questionable if using dockblocs is correct in some cases (like in views, where there is no structural element to document), and some tools complains about it (PHP-CS-Fixer have have fixers for this).

You're right, @rob006 . Switching variable and type order gets Visual Studio Code works.

It's a very interesting tool in views too, because the IDE can autocomplete from the `$variableName`.

Compare this (without phpdoc):

![2020-02-13-181035_976x858_scrot](https://user-images.githubusercontent.com/616169/74459801-316f7f00-4e8c-11ea-943f-091720dd6932.png)

With this (with phpdoc):

![2020-02-13-180915_981x854_scrot](https://user-images.githubusercontent.com/616169/74459851-451ae580-4e8c-11ea-910a-27bc49c2f6e6.png)

**Comment by samdark** [comment]
That's how it should always work and it works like that in PhpStorm, PDT, NetBeans.

**Comment by pigochu** [comment]
@samdark 

https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md

PSR-5 use /** @var ... */ , ex /** @var \Sqlite3 $sqlite */

I changed my IDE from netbeans to vs code , because Netbeans is slow and not support WSL.
but vs code only support   /** @var \Sqlite3 $sqlite */

Does yii2/yii3 follow the PSR-5 specification ?

**Comment by samdark** [comment]
No, it doesn't since PSR-5 isn't accepted yet and IDEs aren't ready.
