### ISSUE TITLE
className()  appear method is deprecated

### ISSUE THREAD

**Issue by haohetao** [yiisoft/yii2-gii#437]
### What steps will reproduce the problem?
Much of the code generated by gii have className() method.
### What's expected?
![图片](https://user-images.githubusercontent.com/4592571/98029737-f4e51880-1e4a-11eb-8116-de7287c5bb7e.png)

### What do you get instead?
using ::class insted of 

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.38
| PHP version      | 7.4,8.0
| Database version | pgsql
| Operating system | none

**Comment by bizley** [comment]
It's because Yii 2 still supports PHP 5.4 and `::class` has been introduced in 5.5.

**Comment by rob006** [comment]
> It's because Yii 2 still supports PHP 5.4 and `::class` has been introduced in 5.5.

It does not mean that Gii needs to generate code for PHP 5.4. Several Yii2 packages increased their PHP requirements, Gii could do the same: https://github.com/yiisoft/yii2-gii/issues/356#issuecomment-504798590

**Comment by bizley** [comment]
I'm all for it but would be nice to do it for all dependent packages.

**Comment by rob006** [comment]
App templates already require PHP 5.6, queue extension requires PHP 5.5. Are there any other official extensions that depends on Gii?

**Comment by bizley** [comment]
@samdark what do you think? Are we upgrading dependants? And to which PHP version?

**Comment by haohetao** [comment]
No one is using php5.4 now

**Comment by samdark** [comment]
@bizley it is OK to upgrade apps since new apps are usually started with new PHP versions but I'm not so sure about Gii generating PHP 5.5+ syntax. From my experience, there are always projects with ancient PHP versions on the server that are, nevertheless, being in constant development.

**Comment by rob006** [comment]
@samdark They can always use old Gii targeting PHP 5.4 syntax. There is no point in making this package less convenient for 99% of users only because someone stuck on PHP 5.4.

**Comment by samdark** [comment]
If that's configurable then I'm all for it.

**Comment by bizley** [comment]
@samdark I'm all for upgrade, If this would be possible I would upgrade to 7.4 ;)
@haohetao you would be surprised how many people are using old unsupported versions of PHP...
