### ISSUE TITLE
Model generator ignore checkbox Singularize

### ISSUE THREAD

**Issue by WinterSilence** [yiisoft/yii2-gii#439]
> For example, table names like <code>some_tables</code> will have class names <code>SomeTable</code>.

### What steps will reproduce the problem?

1. Open page `gii/model` in browser
2. Check Singularize
3. Select table name, in my case it's "caterories"

### What's expected?

`Model Class Name` auto sets as `Caterories`. I check code - class name generated in JS and ignore Singularize

### What do you get instead?

Class name must be set manually by `yii\gii\generators\model\Generator::generateClassName()` as `Category`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.40, gii 2.2.1
| PHP version      | 7.3
| Database version | msql8
| Operating system | Win10

**Comment by samdark** [comment]
@WinterSilence any idea about the fix?

**Comment by WinterSilence** [comment]
@samdark append ajax action returned generateClassName(). I'm install yii2 2 days ago :)

**Comment by WinterSilence** [comment]
@samdark fix #447

**Comment by WinterSilence** [comment]
@samdark are we waiting for?

**Comment by samdark** [comment]
Code review. I'll do it soon. It's in my queue.

![image](https://user-images.githubusercontent.com/47294/113519698-93aaa800-9596-11eb-89b9-610a7c798987.png)

**Comment by samdark** [comment]
Why closing? PR is still open, isn't it?

**Comment by WinterSilence** [comment]
@samdark bug fixed, PR approved, nothing to discuss here

**Comment by samdark** [comment]
@WinterSilence we usually keep the issue open until it's solved in master branch.
