### ISSUE TITLE
Error at update by Composer

### ISSUE THREAD

**Issue by WinterSilence** [yiisoft/yii2-gii#442]
### What steps will reproduce the problem?

I copy repository by git and run `composer update` to load vendor stuff, but installation failed:
~~~
 [Exception]
  Cannot apply patch Fix PHP 7 compatibility (https://yiisoft.github.io/phpunit-patches/phpunit_php7.patch)!
~~~
`patch` no exists in Windows CMD, need you something like "git bash"

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | no installed yet
| PHP version      | 7.3
| Database version | no matter
| Operating system | windows 10

**Comment by samdark** [comment]
You need git installed.

**Comment by WinterSilence** [comment]
@samdark  problem in you fixes for php 7/8, they use Linux commands. Windows and IDE's use `cmd.exe` as default shell, but cmd don't use linux commands/scripts as `patch` and failed update. Add notice for Windows users about using `git-bash.exe` instead `cmd.exe` to run `composer update`

**Comment by samdark** [comment]
I see. I wonder where to add notice though.

**Comment by WinterSilence** [comment]
@samdark to `readme.md` #installation

**Comment by samdark** [comment]
But that's not about installing the package for development. That's usage information.

**Comment by WinterSilence** [comment]
@samdark what's [this](https://github.com/yiisoft/yii2-gii#installation)?

**Comment by samdark** [comment]
That's installation as a part of the application. It won't install dev dependencies.

**Comment by WinterSilence** [comment]
@samdark you killing me slow.. we can [patch patcher](https://github.com/cweagans/composer-patches/blob/master/src/Plugin/Patches.php#L506): 
```php
$io->write('<error>' . $data . (PATH_SEPARATOR == ';' ? ' Add C:\Program Files\Git\usr\bin to PATH' : '') . '</error>');
```

**Comment by samdark** [comment]
Yeah. That's good idea but since patcher isn't part of Yii, it needs to go through patcher issues.

**Comment by WinterSilence** [comment]
@samdark hm.. i think you don't understand me
~~~json
{
   "extra": {
       ...
        "composer-exit-on-patch-failure": false,
        "patches": {
            "cweagans/composer-patches": {
                "Fix Win compatibility": "...",
            },
            ...
        }
    }
}
~~~

**Comment by samdark** [comment]
You mean turning off exit on patch failure? That will cause inability to run tests and that's better to fail right away. Anyway, that is relevant only when you install yii2-gii as developer, not when you use the package.

**Comment by WinterSilence** [comment]
@samdark wake up! and read again, patch:
~~~php
$io->write('<error>' . $data . '</error>');
~~~
replace to
~~~php
$io->write('<error>' . $data . (PATH_SEPARATOR == ';' ? ' Add C:\Program Files\Git\usr\bin to PATH' : '') . '</error>');
~~

**Comment by bizley** [comment]
Hey, what kind of dialog is this? Please keep it civil and respectful.

**Comment by WinterSilence** [comment]
@bizley this is incentive, not an insult - as "just do it!"

**Comment by samdark** [comment]
https://github.com/cweagans/composer-patches/blob/master/src/Plugin/Patches.php#L506 is not my repository it's https://github.com/cweagans. I do not control him or his code.

**Comment by samdark** [comment]
Also, you can't patch the patcher using patcher (as far as I know) because it works before being patched.

**Comment by WinterSilence** [comment]
@samdark `phpunit/*` too not your repositories but they are patched (:

> can't patch the patcher using patcher 

then plan B:

~~~json
{
    "scripts": {
        "post-package-install": [
            "php -r \"{patch the patcher}\"
        ]
    }
}
~~~

**Comment by samdark** [comment]
Might work. Do you want to try implementing it?

**Comment by WinterSilence** [comment]
uncompressed code for review:
~~~php
$path = is_dir(__DIR__.'/vendor') ? __DIR__.'/vendor' : '..';
$path .= '/cweagans/composer-patches/src/Plugin/Patches.php';
$lines = file($path);
$lines[438] = str_replace(
  '</error>',
  '.(PATH_SEPARATOR == ";" ? " Add C:\Program Files\Git\usr\bin to PATH" : "").</error>'
  $lines[438]
);
file_put_contents($path, $lines);
~~~

**Comment by samdark** [comment]
What a mess, to be honest :) Maybe it's better to send a pull request to original repository?

**Comment by WinterSilence** [comment]
@samdark "better" is not change external packages as it is now

**Comment by samdark** [comment]
@WinterSilence yeah but we can't since the range of supported PHP versions is bigger than PHPUnit's so we have to patch it.

**Comment by WinterSilence** [comment]
@samdark you use patcher required php5.6, but you don't want use phpunit 5.7 without any patches?

**Comment by samdark** [comment]
We test Yii 2 on 5.4 - 8. See https://phpunit.de/supported-versions.html

**Comment by WinterSilence** [comment]
@samdark already, PHPUnit 5 | PHP 5.6

**Comment by My6UoT9** [comment]
Just make a PR there https://github.com/cweagans/composer-patches
