### ISSUE TITLE
BUG: `yii\gii\generators\model\generator\generateClassName` cache

### ISSUE THREAD

**Issue by WinterSilence** [yiisoft/yii2-gii#446]
### What steps will reproduce the problem?

~~~php
$tableName = 'posts';
$generator->singularize = false;
var_dump($generator->generateClassName($tableName));
$generator->singularize = true;
var_dump($generator->generateClassName($tableName));
~~~

### What's expected?

return 'posts' and 'posts' 

### What do you get instead?

return 'posts' and 'post' 

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | any
| PHP version      | any
| Database version | any
| Operating system | any

**Comment by bizley** [comment]
How is this a bug? It's singularized.

**Comment by WinterSilence** [comment]
@bizley it's cached at first calling and ignore property changes
@samdark why closed?

**Comment by bizley** [comment]
How do you use it to end with such result?

**Comment by WinterSilence** [comment]
@bizley check example, I'm try generates class names for all cases (`standardizeCapitals`, `singularize`)

**Comment by bizley** [comment]
Yes, but this method is not public, and the cache works properly as far as I see, it checks if name was generated during the script run. I'm not sure how could you run it twice during the same run. That is why I'm asking.

**Comment by WinterSilence** [comment]
@bizley I'm extend generator and add public method `actionClassNames`

**Comment by bizley** [comment]
I would like to see your code.

**Comment by WinterSilence** [comment]
@bizley 
~~~php
<?php

app\gii\generators\model;

/**
 * Application model generator.
 */
class Generator extends \yii\gii\generators\model\Generator
{
    /**
     * Generates class names.
     * 
     * @return string
     */
    public function actionClassNames(): string
    {
        $result = [];
        $result[] = $this->generateClassName($this->tableName);
        $this->standardizeCapitals = true;
        $result['standardizeCapitals'] = $this->generateClassName($this->tableName);
        $this->singularize = true;
        $result['standardizeCapitals_singularize'] = $this->generateClassName($this->tableName);
        $this->standardizeCapitals = false;
        $result['singularize'] = $this->generateClassName($this->tableName);
        return json_encode($result);
    }
}
~~~

**Comment by samdark** [comment]
@WinterSilence solved?

**Comment by WinterSilence** [comment]
@samdark  nope, fix it for self

**Comment by samdark** [comment]
OK. We'll keep the issue open then.

**Comment by bizley** [comment]
I've run this code. This is the result:

```
{
    "0": "Posts",
    "standardizeCapitals": "Posts",
    "standardizeCapitals_singularize": "Posts",
    "singularize": "Posts"
}
```

So... I'm not sure what is going on here but it's @WinterSilence that needs to fix it on his own.
