### ISSUE TITLE
Allow CRUD generator to work with non-ActiveRecord

### ISSUE THREAD

**Issue by WinterSilence** [yiisoft/yii2-gii#452]
1. Generator use table schema instead defined model in `generate*` methods: labels, rules, relations - all that are ignored
2. Table columns it's not same to model attributes:
`Generator::getColumnNames()` return `return $model->attributes();`? 
or
~~~php
public function getSearchAttributes()
{
    return $this->getColumnNames();
}
~~~
3. Base model class not defined:
`'modelClass' => 'This is the ActiveRecord class associated with the table that CRUD will be built upon.`
~~~php
public function rules()
{
    ...
    `[['modelClass'], 'validateClass', 'params' => ['extends' => BaseActiveRecord::className()]],`
    ...
 }
~~~
~~~php
public function getColumnNames()
{
    /* @var $class ActiveRecord */
    $class = $this->modelClass;
    if (is_subclass_of($class, 'yii\db\ActiveRecord')) {
        return $class::getTableSchema()->getColumnNames();
    }
    /* @var $model \yii\base\Model */
    $model = new $class();
    return $model->attributes();
}
~~~
`$model \yii\base\Model` or `is_subclass_of($class, 'yii\db\ActiveRecord')`? wait, what's about `rules()`?!
~~~php
public function validateModelClass()
{
    /* @var $class ActiveRecord */
    $class = $this->modelClass;
    $pk = $class::primaryKey();
    if (empty($pk)) {
        $this->addError('modelClass', "The table associated with $class must have primary key(s).");
    }
}
~~~
How string `$this->modelClass` convert to `$class ActiveRecord`? Method `primaryKey()` defined in `ActiveRecord`!

4. Display attributes signed to foreign keys as columns of related models/tables
  - in "index" widget: `ListView` - valid, `GridView` - invalid
  - in form: invalid, it's must be `dropdownList()` instead input text

5. Unfixed list of *View widgets, need append something like this:
~~~php
/**
 * @string string[] Allowed widgets for index view
 */
public $indexWidgetTypes = [
    'grid' => 'yii\widgets\GridView',
    'list' => 'yii\widgets\ListView',
];
~~~

**Comment by bizley** [comment]
I'm not sure what you want to achieve here. You do realize that using Gii is not required to create Yii files?

**Comment by WinterSilence** [comment]
@bizley can you explain you idea? i display problems in crud generator as unfixed root class of model.

**Comment by bizley** [comment]
I don't understand what you mean by "Base class model not fixed". Please elaborate.

**Comment by bizley** [comment]
Oh, and you don't have to call me in every post with `@`  - I will see all the answers, no worries.

**Comment by WinterSilence** [comment]
@bizley >Oh, and you don't have to call me in every post with @ - I will see all the answers, no worries.
i do it when i want say something to you, not to all owners

**Comment by WinterSilence** [comment]
@bizley you can't understand what's wrong in code examples in 1.?

**Comment by bizley** [comment]
@WinterSilence I have asked about "Base class model not fixed" and it's in 2. Can't you understand what I'm asking?

**Comment by WinterSilence** [comment]
@bizley if you not [package contributor](https://github.com/yiisoft/yii2-gii/graphs/contributors), then you can not post your "I don't understand" and "what's you mean". We understand what's you don't understand, but don't know how help you.

**Comment by WinterSilence** [comment]
@bizley my fail, i mean 2.

**Comment by WinterSilence** [comment]
@bizley  you don't reviewed package code and don't understand me now.

**Comment by WinterSilence** [comment]
@bizley if your model extended `BaseActiveRecord` that's does not guarantee existence of a method `primaryKey()` called in `Generator::validateModelClass()` and other methods.

**Comment by bizley** [comment]
I'm not sure if this is done on purpose or not, because you are not an English speaker, but you are the most difficult to talk to individual I've met in 20 years. You are constantly condescending, you cannot explain properly what you try to improve or change, your tone just insults others all the time, you open PRs that you close out of spite after we show that you made an error, you are basically wasting the developers time, when we genuinely trying to understand what you want to do, and help to speed up the process.
I'm so trying to lessen the burden of maintaining Yii 2 that is on Samdark but I cannot work with you anymore. I'm done here.

**Comment by WinterSilence** [comment]
@bizley
> You are constantly condescending

look to your first comments (:

>  you open PRs that you close out of spite after we show that you made an error

what's PR?

**Comment by WinterSilence** [comment]
@bizley
> I'm so trying to lessen the burden of maintaining Yii 2 

it's good, but you don't try look package code before ask something. I must explain obvious things to you, that's not good.

**Comment by WinterSilence** [comment]
@samdark please delete irrelevant flame

**Comment by samdark** [comment]
Alright. Finally got the idea/use-case.

What's @WinterSilence is trying to achieve is CRUD to work with non-ActiveRecord but just any model.

**Comment by samdark** [comment]
@WinterSilence would you please make points 4 and 5 a separate issues? These aren't really realated to the other points.
