### ISSUE TITLE
Getting unknown property: ControllerNameController::request

### ISSUE THREAD

**Issue by Sensetivity** [yiisoft/yii2-gii#457]
### What steps will reproduce the problem?
Generate a crud
### What's expected?
Properly working page
### What do you get instead?
I get error: Getting unknown property: app\controllers\administration\ActionController::request
Problem line: https://github.com/yiisoft/yii2-gii/commit/ef0ea5fa8db7a77c7e801f637fb67cdfba479c45#diff-9dffc1374993f648b11d21a2b4e50c1fce279a504e0b60fc82b95fbd9fcce278R73
![image](https://user-images.githubusercontent.com/4289543/122566384-2ca67680-d050-11eb-9d68-76dbd8f83218.png)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.20
| Gii version      | 2.2.2
| PHP version      | 7.4.3
| Database version | 
| Operating system |

**Comment by bizley** [comment]
Does this controller use `init()` method? If so - does it call `parent::init()` in it?

**Comment by Sensetivity** [comment]
> Does this controller use `init()` method? If so - does it call `parent::init()` in it?

Yes it use init() method and yes it call parent::init();
```
    public function init()
    {
        parent::init();
        Yii::$app->params['maxFileSizeInBytes'] = \app\helpers\AskHRHelper::getPostMaxSize()['postMaxSizeInBytes'];
        Yii::$app->params['maxFileSizeInMegaBytes'] = \app\helpers\AskHRHelper::getPostMaxSize()['postMaxSizeInMegaBytes'];
        Yii::setAlias('@root', realpath(dirname(__FILE__) . '/../')); // Should return path to root folder. 
    }
```

**Comment by bizley** [comment]
Hmm, does it extend `yii\base\Controller` or its children classes?

**Comment by bizley** [comment]
Oh, you are using Yii 2.0.20

**Comment by bizley** [comment]
This property was added in 2.0.36. Please upgrade.
