### ISSUE TITLE
Gii only works for tables with ID as a PK?

### ISSUE THREAD

**Issue by vicnete** [yiisoft/yii2-gii#463]
I am using https://www.yiiframework.com/doc/guide/2.0/en/start-databases as a starting point. 

It recommends to create a table with the following structure 
CREATE TABLE `country` (
  `code` CHAR(2) NOT NULL PRIMARY KEY,
  `name` CHAR(52) NOT NULL,
  `population` INT(11) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

I can then create a model and the CRUD methods using the gii generator.

The issue is that the generated code refers to id as a primary key at all times, not the case due to the suggested table structure, and even the findModel needs to be updated from.

```
protected function findModel($code)
 {
    if (($model = Country2::findOne($id)) !== null) {
        return $model;
    }

    throw new NotFoundHttpException('The requested page does not exist.');
} 
```
To
```

 protected function findModel($code)
 {
    if (($model = Country2::findOne($code)) !== null) {
        return $model;
    }

    throw new NotFoundHttpException('The requested page does not exist.');
}
```

This makes everything work once you create a Country and you can edit it, delete it... 

The issue now is with the basic gridview on index where every action has an id tacked on to it.

ie https://localhost/tutorialYii/web/index.php?r=country2%2Fview&id=12 rather than https://localhost/tutorialYii/web/index.php?r=country2%2Fview&code=12

I understand this can be fixed by using id as the primary key,done so to test it worked, but I would like to understand how to address the issue of using a custom primary key rather than the standard one.

I know the workaround of using id as a PK, I would just like to understand how to get a gridview that works as intended with a different PK.

**Comment by vicnete** [comment]
Here is my current workaround to get the code from the guide to work. 

This would need to be updated for each case and it assumes the model has been called country as suggested in the guide. 

A fix is needed but this should get most of the people starting with git moving on to the next thing until one is released.

 [
                'class' => 'yii\grid\ActionColumn',
                'header' => 'Actions',
                'headerOptions' => ['style' => 'color:#337ab7'],
                'template' => '{view}{update}{delete}',
                'urlCreator' => function ($action, $model, $key, $index) {
                  if ($action === 'view') {
                      $url ='index.php?r=country/view&code='.$model->code;
                      return $url;
                  }
      
                  if ($action === 'update') {
                      $url ='index.php?r=country/update&code='.$model->code;
                      return $url;
                  }
                  if ($action === 'delete') {
                    $url ='index.php?r=country/delete&code='.$model->code;
                    return $url;
                  }
      
                }
                ],
        ],

**Comment by cjrf** [comment]
I believe this is related to Fix #453, which removed a special case from method generateActionParams() in file generators/crud/Generator.php.

**Comment by samdark** [comment]
@cjrf do you have time for a pull request adding this special case back?

**Comment by cjrf** [comment]
Done

**Comment by WinterSilence** [comment]
I miss fix view https://github.com/yiisoft/yii2-gii/blob/master/src/generators/crud/default/controller.php#L181
