### ISSUE TITLE
Relation duplicates with model generator

### ISSUE THREAD

**Issue by sanyisasha** [yiisoft/yii2-gii#464]
### What steps will reproduce the problem?
Have a table with multiple foregin key
### What's expected?
Only one relation, or better naming, or at least something.
Another possibility to add the foregin key to it somehow. In my case:
```php
public function getCreatedByArticles()
// or
public function getArticlesCreatedBy()

// Property:
* @property Article[] $createdByArticles
// or
* @property Article[] $articlesCreatedBy
```
I can imagine a "found multiple relation, what to do with?" or a similar solution like "Generate Junction Relations As":
What do to with multiple relation?
- Add a number as suffix
- Add the foregin key before
- Add the foregin key after
- Only add first apperance
### What do you get instead?
 I use a modified model generator (I checked with the original, same result) and it's mess it up. Like i got `use` duplicates, and weird, not expected methods like 
```php
public function getArticles0()
```
```php
/**
 * @property Article[] $articles
 * @property Article[] $articles0
 */
```

### Additional info

Foregin keys:
```php
$this->addForeignKey('FG_ARTICLE_CREATED_BY', 'article', 'created_by', 'user', 'id');
$this->addForeignKey('FG_ARTICLE_UPDATED_BY', 'article', 'updated_by', 'user', 'id');
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.43-dev
| PHP version      | 8.0.9
| Database version | 10.1.32-MariaDB
| Operating system | Windows 10

**Comment by WinterSilence** [comment]
1. not all DB engines supports multi-key foreign keys
2. `$this->addForeignKey('FG_ARTICLE_UPDATED_BY', 'article', 'updated_by', 'user', 'id');` is wrong because user column can't be in 2 keys and must be separate

**Comment by sanyisasha** [comment]
@WinterSilence
1. There should be a way to check if the DB engine support it
2. Why it is wrong? Never used this kind of foreign key, but it's almost generate it as expected.

**Comment by sanyisasha** [comment]
This is the generated full code for this example:
```php
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getArticles()
    {
        return $this->hasMany(Article::className(), ['created_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getArticles0()
    {
        return $this->hasMany(Article::className(), ['updated_by' => 'id']);
    }

```

**Comment by WinterSilence** [comment]
@sanyisasha 2. maybe I'm wrond understand you: `user` is creator id similar to created_by? `updated_by` is user id who updated row?

**Comment by sanyisasha** [comment]
> @sanyisasha 2. maybe I'm not understand you: `user` is creator's id and similar to created_by? `updated_by` is user id who updated row?

`created_by` is set when row is created in site.
`updated_by` is when someone like change the title or content of the article.

**Comment by WinterSilence** [comment]
@sanyisasha `ActiveRecord` is only proxy for DB, only way to check it - execute sql.

**Comment by WinterSilence** [comment]
@sanyisasha `user`?

**Comment by WinterSilence** [comment]
@sanyisasha can you post sql dump for table and fk's?

**Comment by WinterSilence** [comment]
@sanyisasha also, you must understand: gii not supported all sql features and can't do it, but you can add custom generator/views do extends gii or you you can fix it and send PR

**Comment by sanyisasha** [comment]
I already use a custom generator, and i think i will fix it myself then. Thanks.

**Comment by WinterSilence** [comment]
@sanyisasha can you public your solution?
