### ISSUE TITLE
Gii CRUD Generator can't update and delete

### ISSUE THREAD

**Issue by Rocky-17** [yiisoft/yii2-gii#473]
```
# database：mysql 5.7.26
CREATE TABLE `country` (
  `code` CHAR(2) NOT NULL PRIMARY KEY,
  `name` CHAR(52) NOT NULL,
  `population` INT(11) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `country` VALUES ('AU','Australia',18886000);
······
```

### What steps will reproduce the problem?
I used Gii CRUD Generator, it seems that list 、search and creat are work well, but if i want to update、view and delete a value,I got a Bad Request (#400),Missing required parameters: code;
The URL is http://localhost/index.php?r=country%2Fview&id=AU  
But if I change the URL to http://localhost/index.php?r=country%2Fview&code=AU  
I got this info:Not Found (#404),The requested page does not exist.

### What's expected?
I wonder why the code generated by the GII crud generator doesn't always work well.  Did I use it improperly in some places?
And how can I fix it？Thanks very much!

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |2.0.43
| PHP version      |7.3.4
| Database version |mysql 5.7.26
| Operating system |windows10

**Comment by bizley** [comment]
If I remember correctly Gii is not modifying the standard action that expects `id` to be `integer` and you need to update it yourself. Unless it will be changed by some friendly developer with PR.

**Comment by WinterSilence** [comment]
un-public fix https://github.com/yiisoft/yii2-gii/pull/470

**Comment by bizley** [comment]
Ok, closing for now then.
