### ISSUE TITLE
Can't access the page when the table related contains underscores

### ISSUE THREAD

**Issue by ruffiem** [yiisoft/yii2-gii#49]
I fooled around and created 3 tables : 

test_with_underscore
test_underscore
testnoscore

The generators creates the files correctly for all 3 tables but when I try to access the page, only testnoscore shows up. The other two show an error, for test_underscore it will be : 

```
An Error occurred while handling another error:
exception 'yii\base\InvalidRouteException' with message 'Unable to resolve the request: spa/error' in /usr/local/var/www/wip/mrvyii/vendor/yiisoft/yii2/base/Controller.php:122
Stack trace:
#0 /usr/local/var/www/wip/mrvyii/vendor/yiisoft/yii2/base/Module.php(455): yii\base\Controller->runAction('error', Array)
#1 /usr/local/var/www/wip/mrvyii/vendor/yiisoft/yii2/web/ErrorHandler.php(80): yii\base\Module->runAction('spa/error')
#2 /usr/local/var/www/wip/mrvyii/vendor/yiisoft/yii2/base/ErrorHandler.php(101): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#4 {main}
Previous exception:
exception 'yii\base\InvalidRouteException' with message 'Unable to resolve the request "testUnderscore".' in /usr/local/var/www/wip/mrvyii/vendor/yiisoft/yii2/base/Module.php:461
Stack trace:
#0 /usr/local/var/www/wip/mrvyii/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('testUnderscore', Array)
#1 /usr/local/var/www/wip/mrvyii/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#2 /usr/local/var/www/wip/mrvyii/web/index.php(12): yii\base\Application->run()
#3 {main}

Next exception 'yii\web\NotFoundHttpException' with message 'Page not found.' in /usr/local/var/www/wip/mrvyii/vendor/yiisoft/yii2/web/Application.php:96
Stack trace:
#0 /usr/local/var/www/wip/mrvyii/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 /usr/local/var/www/wip/mrvyii/web/index.php(12): yii\base\Application->run()
#2 {main}
```

The DB is MySQL and the table scheme has 3 elementary columns (id, col1, col2).

**Comment by samdark** [comment]
1. Please provide SQL to create schema and add some data.
2. Please provide data you've entered into forms.
3. Please provide URL of the page accessed.

**Comment by ruffiem** [comment]
Hey Sam,

Here we go : 

**Tables**
```
CREATE TABLE `test_underscore` (
  `idtest` int(11) NOT NULL,
  `coltest` varchar(45) DEFAULT NULL,
  `coltest1` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`idtest`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `testnounder` (
  `idtest` int(11) NOT NULL,
  `coltest` varchar(45) DEFAULT NULL,
  `coltest1` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`idtest`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `test_underscore` (
  `idtest` int(11) NOT NULL,
  `coltest` varchar(45) DEFAULT NULL,
  `coltest1` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`idtest`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
````

**Model generator**

Data from automation :
* test_with_underscore gives TestWithUndercore as the Model classname.
* test_underscore gives TestUnderscore as the Model Classname.
* testnounder gives Testnounder as the Model Classname

**CRUD generator**

Example for test_with_underscore :
![sample](https://cloud.githubusercontent.com/assets/1785492/7798337/e4123088-02f8-11e5-9fdb-51c8bcdc9cd3.png)

**Links**

* http://localhost:8081/testnounder (works)
* http://localhost:8081/testUnderscore (error)
* http://localhost:8081/testWithUnderscore (error)

**Data**

No sample data.

**Comment by samdark** [comment]
Thanks!

**Comment by ruffiem** [comment]
I can take care of it if you want ^^

**Comment by samdark** [comment]
Yes, that would be great.

**Comment by ruffiem** [comment]
I'm on it. Were you able to reproduce the issue ? Or anyone else out there ?

**Comment by samdark** [comment]
I haven't tried yet.

**Comment by wildgras** [comment]
I have the same issue. Is there a solution for this?

**Comment by jeicd** [comment]
I couldn't reproduce the bug. I presume he is using wrong controller IDs: testUnderscore must be test-underscore and testWithUnderscore must be test-with-underscore.

**Comment by sucoec** [comment]
Hi... i have the same issue do i have to add underscore in controller and view folder?

Here is my stack trace:

`yii\base\InvalidRouteException: Unable to resolve the request "tfinxmlsri/index". in C:\xampp\htdocs\facturas_seted\vendor\yiisoft\yii2\base\Module.php:532
Stack trace:
#0 C:\xampp\htdocs\facturas_seted\vendor\yiisoft\yii2\web\Application.php(102): yii\base\Module->runAction('tfinxmlsri/inde...', Array)
#1 C:\xampp\htdocs\facturas_seted\vendor\yiisoft\yii2\base\Application.php(380): yii\web\Application->handleRequest(Object(yii\web\Request))
#2 C:\xampp\htdocs\facturas_seted\web\index.php(12): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Página no encontrada. in C:\xampp\htdocs\facturas_seted\vendor\yiisoft\yii2\web\Application.php:114
Stack trace:
#0 C:\xampp\htdocs\facturas_seted\vendor\yiisoft\yii2\base\Application.php(380): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 C:\xampp\htdocs\facturas_seted\web\index.php(12): yii\base\Application->run()
#2 {main}`

**Comment by MKiselev** [comment]
@jeicd 's right!

The controller id must be delimiter with `-` symbol, because here https://github.com/yiisoft/yii2/blob/master/framework/base/Module.php#L631 controller id will be exploded and will uppercased first letter.

If you wanna use camelCase in your routes, you can write url rules like `'testWithUnderscore/<action:\w+>' => 'test-with-underscope/<action>',`

If you wanna use camelCase in path to your views, just set `viewPath` in controller like this:
```php
$this->viewPath = $this->module->getViewPath() . DIRECTORY_SEPARATOR . 'testWithUnderscore';
```
or you can override `getViewPath` method.

to @sucoec @wildgras @ruffiem
