### ISSUE TITLE
need checkAccessCallback

### ISSUE THREAD

**Issue by nazbav** [yiisoft/yii2-gii#492]
### What's expected?

checkAccessCallback in yii\gii\Module (like in yii\debug\Module)

### What do you get instead?

Nothing 🤔

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.14
| PHP version      | 8.0
| Database version | MySQL 5.7
| Operating system | Ubuntu 18.06

**Comment by bizley** [comment]
This will not be added - Gii should not be accessed by anyone other than developer in the developing environment - it is not meant for the production one.
