### ISSUE TITLE
Enh: Redirect to previous page after update

### ISSUE THREAD

**Issue by robsch** [yiisoft/yii2-gii#496]
What do you think about this little enhancement on controller creation for the update action? 

```php
public function actionUpdate($id)
{
    $model = $this->findModel($id);

    if(Yii::$app->request->isGet) {
        Url::remember($this->request->referrer, 'url-before-update');
    }

    if ($model->load(Yii::$app->request->post()) && $model->save()) {
        return $this->redirect(
            Url::previous('url-before-update') ?: ['view', 'id' => $model->id]
        );
    }

    return $this->render('update', [
        'model' => $model,
    ]);
}
```

With this a user should be redirected to the previous page and not always to the view page. Very likely that that the user has clicked the edit button in the index page (with a GridView or ListView) and wants to return to this page. But then it doesn't matter where the user came from. It should always work.

Is this a sound enhancement of gii?

Suggested this also on https://stackoverflow.com/a/70802807/57091.

**Comment by samdark** [comment]
Yes, that should work.

**Comment by robsch** [comment]
This could be used for delete actions as well.

**Comment by schmunk42** [comment]
We had that in **giiant** and removed it, since it's a mess when using multiple tabs.

**Comment by samdark** [comment]
@schmunk42 would you please elaborate about mess?

**Comment by schmunk42** [comment]
1) Tab 1: Navigate from /index to /update?id=1
2) Tab 2: Navigate from /view?id=2 to /update?id=2
3) Tab 1: click save -> redirect to /view?id=2 - but you'd expect /index

**Comment by samdark** [comment]
Hmm... yeah. @robsch do you still want it?

**Comment by robsch** [comment]
Hm, I thought it already, that it is not 100 percent perfect. Though it might be a little problem (How often will this situation occur? And is the advantage more worth than the disadvantage?) it is one nevertheless. I use it, but I can understand that people don't want this behaviour. Please decide it by yourself. Not implementing it is at least less work  😉

Still, one improvement was to use `$this->action->uniqueId` instead of the string as the key. But I just thought, would it reasonable to utilize a csrf token for the key? That could overcome the tab issue, since it is unique for a single submit.

**Comment by samdark** [comment]
CSRF token won't work since it's regenerated at a certain times and, also, it could be turned off. An idea of having a separate ID for each tab is interesting but is quite complicated implementation-wise and isn't needed for many cases. I don't think we want this complexity within generated code since that doesn't suit majority of cases same as just redirecting back.

So decision is to close the issue for now.
