### ISSUE TITLE
composer issue to trim validator

### ISSUE THREAD

**Issue by DZotya** [yiisoft/yii2-gii#508]
https://github.com/yiisoft/yii2-gii/blob/ba7306dd24652507205658e9d1fe9b298156b313/src/generators/crud/Generator.php#L93

for this release it is needed to add the minimum version of yii2 being 2.0.46 includes already TrimValidator

**Comment by samdark** [comment]
Was already done in https://github.com/yiisoft/yii2-gii/commit/c9efc088cd7003353125b2a2cc696d4b1028eafc
