### ISSUE TITLE
parent::init() should be called in yii\gii\components\ActiveField::init()

### ISSUE THREAD

**Issue by SOHELAHMED7** [yiisoft/yii2-gii#529]
In file yii\gii\components\ActiveField

`parent::init()` should be called

```diff
/**
     * {@inheritdoc}
     */
    public function init()
    {
+      parent::init();
        $stickyAttributes = $this->model->stickyAttributes();
        if (in_array($this->attribute, $stickyAttributes, true)) {
            $this->sticky();
        }
```

**Comment by bizley** [comment]
True, but in this specific case it's not needed as I see. Or am I missing something?

**Comment by SOHELAHMED7** [comment]
Its not needed here because implementation of parent classes is empty. But in future if the parent class add some code in `init()` then it wont have any effect and might lead to bug.

I think, normally Yii community have a habit of calling `parent::init()` in `init()` of child class so I think it is ideal to have

**Comment by bizley** [comment]
All you say is true. Do you have time to create a PR?

**Comment by SOHELAHMED7** [comment]
Yes
