### ISSUE TITLE
Exist rules for foreign keys - namespace

### ISSUE THREAD

**Issue by glasmasin** [yiisoft/yii2-gii#72]
I'm not sure if I've missed something (due to customisation) but the new exist rules are causing errors due to the $refClassName *not* being fully qualified. Is this expected behaviour, because I can code a workaround in my custom code, but thought I'd point it out in case of errors for other users.

**Comment by Faryshta** [comment]
what errors are you getting?

**Comment by cebe** [comment]
@glasmasin please show the code that is generated and also specify the error in detail.

**Comment by glasmasin** [comment]
@cebe, @Faryshta 

Sorry - was logged into the work account, so didn't get any messages. 

The generated code was:
<pre>
[['gender_id'], 'exist', 'skipOnError' => true, 'targetClass' => Gender::className(), 'targetAttribute' => ['id']],
</pre>
Rather than:
<pre>
[['gender_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\admin\models\lib\Gender::className(), 'targetAttribute' => ['id']],
</pre>

Called from \app\modules\personnel\models\Persondetails

With the error:
<pre>
Class '\app\modules\personnel\models\Gender' not found.
</pre>

I had to create a few workarounds, as we have a complex module system (approx 900 tables). If a normal user is keeping all models in the same namespace, it shouldn't case a problem.

**Comment by cebe** [comment]
hm... not sure if gii will be able to find a class that is in a different namespace...

**Comment by glasmasin** [comment]
No - I had to set up a full class map in advance and use that to work it out. It works fine now though. Once I've had a bit more time to refine it, I'll release the code.
