### ISSUE TITLE
gii model generetor suport migrations create

### ISSUE THREAD

**Issue by lukBarros** [yiisoft/yii2-gii#73]
`gii model generetor suport migrations create

In some cases, many in modeling development environment database using something like mysql workbanch then create efetivamamente at your local bank host to generate the model ( and CRUD ) to that entity.

And, generally , stop redistribute the change to other environments ( dev , test , production) it must generate a migration mnualmente generally .

Ideally, the model generator is given Boolean option (Yes or No) to generate the migration file , ie , the migration to create the table in the up ( ) and nothing in the down ( )

**Comment by samdark** [comment]
Automatic migration generation is quite tricky to achieve and could lead to errors. While definitely worth trying, we aren't going to focus on it anytime soon.

**Comment by Faryshta** [comment]
what would be the logic? generate the migration from the model or from the db table?

**Comment by samdark** [comment]
From difference between DB state at previous migration and current database state.

**Comment by lukBarros** [comment]
Hi mans! 

@Faryshta thanks! Its is 'crazy'? :P

@samdark He understood what I said. Exactly .

@Faryshta genere migration based inverse flow.  Just to avoid tedious manual work.

**Comment by Faryshta** [comment]
@lukBarros if we make the migration based on the model we can use the phpdoc to find the attributes and types or the attributes() method. Then use the attributeLabels() or hints() to generate the comments in a table.

**Comment by samdark** [comment]
@Faryshta nah, he meant generating migrations as diff between current DB schema and its previous state. Something like:

- https://github.com/MihanEntalpo/yii-sql-migration-dump-generator
- https://github.com/MihanEntalpo/yii-sql-migration-generator
- https://github.com/RSol/yii_gii_migrate

**Comment by samdark** [comment]
Here's the one that works: https://github.com/Insolita/yii2-migrik

**Comment by lukBarros** [comment]
Amazing man! Lets run!
