### ISSUE TITLE
Error: yii\db\mysql\Schema does not support fetching all schema names.

### ISSUE THREAD

**Issue by Mirocow** [yiisoft/yii2-gii#74]
ver: 2.0.6-dev
Error: yii\db\mysql\Schema does not support fetching all schema names.

why this code here?
``` php
        if ($schema->hasMethod('getSchemaNames')) { // keep BC to Yii versions < 2.0.4
            try {
                $schemaNames = $schema->getSchemaNames();
            } catch (NotSupportedException $e) {
                // schema names are not supported by schema
            }
        }
```

in the generators\model\Generator.php
https://github.com/yiisoft/yii2-gii/blob/master/generators/model/Generator.php#L387

sorry for bad english

**Comment by Mirocow** [comment]
this bug only if you used PHP ED DBG

**Comment by samdark** [comment]
If it can't be reproduced w/o DBG it means that DBG is executing methods by itself which is certainly won't ever happen normally.
