### ISSUE TITLE
HTML5 input support for form generator

### ISSUE THREAD

**Issue by YaroslavShapoval** [yiisoft/yii2-gii#75]
[See yii2 issue #9348](https://github.com/yiisoft/yii2/issues/9348)

We should update model form generation for support HTML5-types.

For example, for this rule 
```php
[['fieldxyz'], 'integer', 'min' => 10, 'max' => 20]
```
should be generated such as this field
```php
<?= $form->field($model, 'fieldxyz')->input('number', ['min' => 10, 'max' => 20]) ?>
```

**Comment by samdark** [comment]
Nope. It will conflict with JavaScript validation.
