### ISSUE TITLE
yii\gii\generators\model\Generator tableName validation regex

### ISSUE THREAD

**Issue by pyd** [yiisoft/yii2-gii#76]
Hi,
regex for tableName validation has been changed in https://github.com/yiisoft/yii2-gii/commit/06bcd329e6d4748ccbf7e2118b4e89ead80abd34.
Since then validation fails for table name like 'schema.table_name'.

Could you please take a look at this regex https://regex101.com/r/iY6pK8/5:
- it does not allow spaces in schema name
- it does in table name but not as first character

Maybe this validator is not so useful as the validateTableName() method checks for the existence of the table.

Thanks.

**Comment by pyd** [comment]
Sorry,
I missed the asterisk requirement in the regex.

**Comment by samdark** [comment]
Corrected regex. Should be fine now.
