### ISSUE TITLE
Gii generator overrides files, even when instructed not to override

### ISSUE THREAD

**Issue by Coksnuss** [yiisoft/yii2-gii#83]
See title.

Example:
`./yii gii/model --generateQuery --tableName=*`

Output (excerpt):
```
The following files will be generated:
  [...]
  [unchanged] models/Bet.php
    [changed] models/Match.php
Do you want to overwrite this file? [y,n,ya,na,?]: n
  [unchanged] models/Matchday.php
        [new] models/Score.php
    [changed] models/Team.php
Do you want to overwrite this file? [y,n,ya,na,?]: n
    [changed] models/User.php
Do you want to overwrite this file? [y,n,ya,na,?]: n

Ready to generate the selected files? (yes|no) [yes]:y

Files were generated successfully!
Generating code using template "/home/vsx/public_html/clibot/vendor/coksnuss/yii2-gii-modelgen/generators/model/default"...
   [...]
   skipped models/Bet.php
 overwrote models/Match.php
   skipped models/Matchday.php
 generated models/Score.php
 overwrote models/Team.php
 overwrote models/User.php
done!
```

The generator overwrote the files `Match.php`, `Team.php` and `User.php` against the given instructions!

I have not look into the issue yet, but I think the error is in https://github.com/yiisoft/yii2-gii/blob/master/Generator.php#L273, where the comparision of `$answers[$file->id]` is missing. Basically the `isset()` call should be removed.

**Comment by jeicd** [comment]
The same issue as yiisoft/yii2#9163

**Comment by samdark** [comment]
Please check if https://github.com/yiisoft/yii2-gii/pull/69 fixes the issue.

**Comment by Coksnuss** [comment]
Yes, this is exactly what i did to fix the problem.

**Comment by jeicd** [comment]
Checked #69  :-1:. It fixes an issue in console application, but causes a regression in web app.

**Comment by jeicd** [comment]
@Coksnuss yep

**Comment by samdark** [comment]
Merged with adjustments.
