### ISSUE TITLE
Convert backslashes to forward slashes in view paths

### ISSUE THREAD

**Issue by lubosdz** [yiisoft/yii2-gii#97]
Backslashes in view paths should be automatically converted to forward slash to avoid following common issues:
- @app\modules/admin/views/user -> will throw exception invalid alias (note backslash `\`)
- app/modules/admin/views/user  -> will create wrong dirs under `@web/app/modules/admin/views/user`

It is quite common to copy & paste namespaced paths from previous fields, or enter relative path (without @ alias prefix).

**Comment by samdark** [comment]
The issue confirmed in:

- Controller generator view path.
- CRUD generator view path.
- Extension generator output path.
